// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#include "../ui.h"

#ifndef LV_ATTRIBUTE_MEM_ALIGN
    #define LV_ATTRIBUTE_MEM_ALIGN
#endif

// IMAGE DATA: assets/empty_bullet.png
const LV_ATTRIBUTE_MEM_ALIGN uint8_t ui_img_empty_bullet_png_data[] = {
    0x00,0x00,
    //alpha channel data:
    0x00,
};
const lv_image_dsc_t ui_img_empty_bullet_png = {
    .header.w = 1,
    .header.h = 1,
    .data_size = sizeof(ui_img_empty_bullet_png_data),
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .data = ui_img_empty_bullet_png_data
};

