// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#ifndef _DVR_TT01_UI_H
#define _DVR_TT01_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Main.h"
#include "screens/ui_VideoInput.h"
#include "screens/ui_Keyboard.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_record_png);    // assets/record.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets/pause.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_stop_png);    // assets/stop.png
LV_IMG_DECLARE(ui_img_storage_png);    // assets/storage.png
LV_IMG_DECLARE(ui_img_edit_note_png);    // assets/edit_note.png
LV_IMG_DECLARE(ui_img_input_png);    // assets/input.png
LV_IMG_DECLARE(ui_img_space_bar_png);    // assets/space_bar.png
LV_IMG_DECLARE(ui_img_input_done_png);    // assets/input_done.png
LV_IMG_DECLARE(ui_img_shift_lock_png);    // assets/shift_lock.png
LV_IMG_DECLARE(ui_img_backspace_png);    // assets/backspace.png
LV_IMG_DECLARE(ui_img_docs_apps_script_png);    // assets/docs_apps_script.png
LV_IMG_DECLARE(ui_img_format_list_bulleted_add_png);    // assets/format_list_bulleted_add.png
LV_IMG_DECLARE(ui_img_keyboard_png);    // assets/keyboard.png
LV_IMG_DECLARE(ui_img_keyboard_off_png);    // assets/keyboard_off.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
