// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#ifndef _DVR_TT01_UI_H
#define _DVR_TT01_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Main.h"
#include "screens/ui_VideoInput.h"
#include "screens/ui_Keyboard.h"
#include "screens/ui_RecordList.h"
#include "screens/ui_Setting.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_new_png);    // assets/new.png
LV_IMG_DECLARE(ui_img_cancel_png);    // assets/cancel.png
LV_IMG_DECLARE(ui_img_list_png);    // assets/list.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_brand_awareness_png);    // assets/brand_awareness.png
LV_IMG_DECLARE(ui_img_no_sound_png);    // assets/no_sound.png
LV_IMG_DECLARE(ui_img_record_png);    // assets/record.png
LV_IMG_DECLARE(ui_img_pause_png);    // assets/pause.png
LV_IMG_DECLARE(ui_img_play_png);    // assets/play.png
LV_IMG_DECLARE(ui_img_stop_png);    // assets/stop.png
LV_IMG_DECLARE(ui_img_fast_rewind_png);    // assets/fast_rewind.png
LV_IMG_DECLARE(ui_img_fast_forward_png);    // assets/fast_forward.png
LV_IMG_DECLARE(ui_img_storage_png);    // assets/storage.png
LV_IMG_DECLARE(ui_img_usb_png);    // assets/usb.png
LV_IMG_DECLARE(ui_img_edit_note_png);    // assets/edit_note.png
LV_IMG_DECLARE(ui_img_check_circle_png);    // assets/check_circle.png
LV_IMG_DECLARE(ui_img_input_png);    // assets/input.png
LV_IMG_DECLARE(ui_img_arrow_back_png);    // assets/arrow_back.png
LV_IMG_DECLARE(ui_img_arrow_forward_png);    // assets/arrow_forward.png
LV_IMG_DECLARE(ui_img_space_bar_png);    // assets/space_bar.png
LV_IMG_DECLARE(ui_img_shift_lock_png);    // assets/shift_lock.png
LV_IMG_DECLARE(ui_img_backspace_png);    // assets/backspace.png
LV_IMG_DECLARE(ui_img_esc_png);    // assets/esc.png
LV_IMG_DECLARE(ui_img_enter_png);    // assets/enter.png
LV_IMG_DECLARE(ui_img_search_png);    // assets/search.png
LV_IMG_DECLARE(ui_img_check_png);    // assets/check.png
LV_IMG_DECLARE(ui_img_folder_check_png);    // assets/folder_check.png
LV_IMG_DECLARE(ui_img_folder_limited_png);    // assets/folder_limited.png
LV_IMG_DECLARE(ui_img_vertical_align_top_png);    // assets/vertical_align_top.png
LV_IMG_DECLARE(ui_img_arrow_upward_png);    // assets/arrow_upward.png
LV_IMG_DECLARE(ui_img_arrow_downward_png);    // assets/arrow_downward.png
LV_IMG_DECLARE(ui_img_vertical_align_bottom_png);    // assets/vertical_align_bottom.png
LV_IMG_DECLARE(ui_img_replace_video_png);    // assets/replace_video.png
LV_IMG_DECLARE(ui_img_delete_png);    // assets/delete.png
LV_IMG_DECLARE(ui_img_drive_file_move_png);    // assets/drive_file_move.png
LV_IMG_DECLARE(ui_img_dukto_png);    // assets/dukto.png
LV_IMG_DECLARE(ui_img_router_png);    // assets/router.png
LV_IMG_DECLARE(ui_img_sync_png);    // assets/sync.png
LV_IMG_DECLARE(ui_img_router_off_png);    // assets/router_off.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
