// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#include "ui.h"
#include "CommonData.h"
#include "ScreenMapping.h"

void CommonButtonOnClick(lv_event_t* e)
{
    ScreenMapping::GetInstance().SetEvent(*e);
}

void OnLoaded(lv_event_t* e)
{
    // Your code here
}
