// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#include "ui.h"
#include "ScreenMapping.h"

void OnLoaded(lv_event_t* e)
{
    // Your code here
}

void CommonButtonOnClick(lv_event_t* e)
{
    lv_obj_remove_state((lv_obj_t*)(e->current_target), LV_STATE_FOCUSED);
    ScreenMapping::GetInstance().SetEvent(*e);
}

void CommonButtonOnLongPress(lv_event_t * e)
{
    lv_obj_remove_state((lv_obj_t*)(e->current_target), LV_STATE_FOCUSED);
    ScreenMapping::GetInstance().SetEvent(*e);
}

void CommonButtonOnRelease(lv_event_t * e)
{
    lv_obj_remove_state((lv_obj_t*)(e->current_target), LV_STATE_FOCUSED);
    ScreenMapping::GetInstance().SetEvent(*e);
}

void CommonButtonOnLongPressRepeat(lv_event_t * e)
{
    lv_obj_remove_state((lv_obj_t*)(e->current_target), LV_STATE_FOCUSED);
    ScreenMapping::GetInstance().SetEvent(*e);
}
