// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void OnLoaded(lv_event_t * e);
void CommonButtonOnClick(lv_event_t * e);
void CommonButtonOnLongPress(lv_event_t * e);
void CommonButtonOnRelease(lv_event_t * e);
void CommonButtonOnLongPressRepeat(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
