// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#ifndef UI_INFO_H
#define UI_INFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Info
extern void ui_Info_screen_init(void);
extern void ui_Info_screen_destroy(void);
extern void ui_event_Info(lv_event_t * e);
extern lv_obj_t * ui_Info;
extern lv_obj_t * ui_Container16;
extern void ui_event_btnCard1(lv_event_t * e);
extern lv_obj_t * ui_btnCard1;
extern void ui_event_btnCard2(lv_event_t * e);
extern lv_obj_t * ui_btnCard2;
extern void ui_event_btnCard3(lv_event_t * e);
extern lv_obj_t * ui_btnCard3;
extern void ui_event_btnCard4(lv_event_t * e);
extern lv_obj_t * ui_btnCard4;
extern void ui_event_btnCard5(lv_event_t * e);
extern lv_obj_t * ui_btnCard5;
extern void ui_event_btnCard6(lv_event_t * e);
extern lv_obj_t * ui_btnCard6;
extern void ui_event_btnCard7(lv_event_t * e);
extern lv_obj_t * ui_btnCard7;
extern void ui_event_btnCard8(lv_event_t * e);
extern lv_obj_t * ui_btnCard8;
extern void ui_event_btnCard9(lv_event_t * e);
extern lv_obj_t * ui_btnCard9;
extern void ui_event_btnCard10(lv_event_t * e);
extern lv_obj_t * ui_btnCard10;
extern void ui_event_btnCard11(lv_event_t * e);
extern lv_obj_t * ui_btnCard11;
extern void ui_event_btnCard12(lv_event_t * e);
extern lv_obj_t * ui_btnCard12;
extern void ui_event_btnCard13(lv_event_t * e);
extern lv_obj_t * ui_btnCard13;
extern void ui_event_btnBack(lv_event_t * e);
extern lv_obj_t * ui_btnBack;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_imgInfoCardReview;
extern lv_obj_t * ui_lblCardInfoTitle;
extern lv_obj_t * ui_lblPlayer2Charge6;
extern lv_obj_t * ui_lblUsageInfo;
extern lv_obj_t * ui_lblPlayer2Charge7;
extern lv_obj_t * ui_lblStrategyInfo;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

