// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#include "../ui.h"

lv_obj_t * ui_Music = NULL;
lv_obj_t * ui_rlMusicList = NULL;
lv_obj_t * ui_Container19 = NULL;
lv_obj_t * ui_arcTime = NULL;
lv_obj_t * ui_btnPrev = NULL;
lv_obj_t * ui_btnPlay = NULL;
lv_obj_t * ui_btnNext = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_lblMusicTitle2 = NULL;
lv_obj_t * ui_sldVolume = NULL;
lv_obj_t * ui_lblMusicTitle = NULL;
lv_obj_t * ui_btnBack2 = NULL;
// event funtions
void ui_event_Music(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Music_OnLoaded(e);
    }
}

void ui_event_rlMusicList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnPlaylistChange(e);
    }
}

void ui_event_btnPrev(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnMusicControl(e);
    }
}

void ui_event_btnPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnMusicControl(e);
    }
}

void ui_event_btnNext(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        OnMusicControl(e);
    }
}

void ui_event_sldVolume(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        OnVolumeChange(e);
    }
}

void ui_event_btnBack2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_Music_screen_init(void)
{
    ui_Music = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Music, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Music, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Music, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Music, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Music, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Music, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rlMusicList = lv_roller_create(ui_Music);
    lv_roller_set_options(ui_rlMusicList, "Option_1\nOption_2\nOption_3", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rlMusicList, 400);
    lv_obj_set_height(ui_rlMusicList, 480);
    lv_obj_set_x(ui_rlMusicList, -46);
    lv_obj_set_y(ui_rlMusicList, -95);
    lv_obj_set_align(ui_rlMusicList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_rlMusicList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_rlMusicList, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_style_text_color(ui_rlMusicList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rlMusicList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_rlMusicList, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rlMusicList, &ui_font_Arial24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_rlMusicList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rlMusicList, lv_color_hex(0x303030), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rlMusicList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_rlMusicList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_rlMusicList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_Music);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, 400);
    lv_obj_set_height(ui_Container19, 480);
    lv_obj_set_x(ui_Container19, -69);
    lv_obj_set_y(ui_Container19, -50);
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container19, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container19, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_Container19, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container19, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_arcTime = lv_arc_create(ui_Container19);
    lv_obj_set_width(ui_arcTime, 380);
    lv_obj_set_height(ui_arcTime, 380);
    lv_obj_set_x(ui_arcTime, -42);
    lv_obj_set_y(ui_arcTime, 1);
    lv_obj_set_align(ui_arcTime, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_arcTime, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_arcTime, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_arcTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_arc_set_value(ui_arcTime, 0);
    lv_arc_set_bg_angles(ui_arcTime, 275, 265);
    lv_obj_set_style_pad_row(ui_arcTime, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_arcTime, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_arcTime, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_arcTime, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_arcTime, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_btnPrev = lv_button_create(ui_arcTime);
    lv_obj_set_width(ui_btnPrev, 80);
    lv_obj_set_height(ui_btnPrev, 80);
    lv_obj_set_x(ui_btnPrev, 165);
    lv_obj_set_y(ui_btnPrev, 208);
    lv_obj_set_align(ui_btnPrev, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnPrev, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnPrev, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnPrev, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnPrev, lv_color_hex(0x4646FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPrev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnPrev, &ui_img_skip_previous_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPrev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnPrev, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnPrev, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnPrev, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnPrev, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnPrev, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnPrev, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_btnPlay = lv_button_create(ui_arcTime);
    lv_obj_set_width(ui_btnPlay, 110);
    lv_obj_set_height(ui_btnPlay, 110);
    lv_obj_set_x(ui_btnPlay, 165);
    lv_obj_set_y(ui_btnPlay, 208);
    lv_obj_set_align(ui_btnPlay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnPlay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnPlay, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPlay, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_btnPlay, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnPlay, lv_color_hex(0x4646FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnPlay, &ui_img_play_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnPlay, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnPlay, lv_color_hex(0x4646FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnPlay, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_src(ui_btnPlay, &ui_img_pause_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_btnNext = lv_button_create(ui_arcTime);
    lv_obj_set_width(ui_btnNext, 80);
    lv_obj_set_height(ui_btnNext, 80);
    lv_obj_set_x(ui_btnNext, 165);
    lv_obj_set_y(ui_btnNext, 208);
    lv_obj_set_align(ui_btnNext, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnNext, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnNext, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnNext, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnNext, lv_color_hex(0x4646FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnNext, &ui_img_skip_next_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnNext, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnNext, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnNext, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnNext, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnNext, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnNext, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container14 = lv_obj_create(ui_arcTime);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 385);
    lv_obj_set_height(ui_Container14, 75);
    lv_obj_set_x(ui_Container14, -69);
    lv_obj_set_y(ui_Container14, -50);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container14, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_Container14, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container14, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblMusicTitle2 = lv_label_create(ui_Container14);
    lv_obj_set_width(ui_lblMusicTitle2, 40);
    lv_obj_set_height(ui_lblMusicTitle2, 40);
    lv_obj_set_x(ui_lblMusicTitle2, -46);
    lv_obj_set_y(ui_lblMusicTitle2, 183);
    lv_obj_set_align(ui_lblMusicTitle2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMusicTitle2, "");
    lv_obj_remove_flag(ui_lblMusicTitle2,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_image_src(ui_lblMusicTitle2, &ui_img_volume_up_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sldVolume = lv_slider_create(ui_Container14);
    lv_slider_set_value(ui_sldVolume, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_sldVolume) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_sldVolume, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_sldVolume, 250);
    lv_obj_set_height(ui_sldVolume, 20);
    lv_obj_set_x(ui_sldVolume, -135);
    lv_obj_set_y(ui_sldVolume, -9);
    lv_obj_set_align(ui_sldVolume, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_sldVolume, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sldVolume, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_border_color(ui_sldVolume, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_sldVolume, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_sldVolume, 1, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_sldVolume, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_sldVolume,
                                                                                                lv_obj_get_style_pad_right(ui_sldVolume, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lblMusicTitle = lv_label_create(ui_Container19);
    lv_obj_set_width(ui_lblMusicTitle, 400);
    lv_obj_set_height(ui_lblMusicTitle, 80);
    lv_obj_set_x(ui_lblMusicTitle, -46);
    lv_obj_set_y(ui_lblMusicTitle, 183);
    lv_obj_set_align(ui_lblMusicTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblMusicTitle, "");
    lv_obj_remove_flag(ui_lblMusicTitle,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblMusicTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblMusicTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblMusicTitle, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblMusicTitle, &ui_font_Arial24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBack2 = lv_button_create(ui_Music);
    lv_obj_set_width(ui_btnBack2, 50);
    lv_obj_set_height(ui_btnBack2, 50);
    lv_obj_set_x(ui_btnBack2, 372);
    lv_obj_set_y(ui_btnBack2, -212);
    lv_obj_set_align(ui_btnBack2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnBack2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnBack2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBack2, LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_remove_flag(ui_btnBack2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnBack2, lv_color_hex(0x1B7700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnBack2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnBack2, &ui_img_arrow_left_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnBack2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnBack2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnBack2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_btnBack2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_btnBack2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnBack2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnBack2, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_rlMusicList, ui_event_rlMusicList, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPrev, ui_event_btnPrev, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPlay, ui_event_btnPlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnNext, ui_event_btnNext, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_sldVolume, ui_event_sldVolume, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnBack2, ui_event_btnBack2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Music, ui_event_Music, LV_EVENT_ALL, NULL);

}

void ui_Music_screen_destroy(void)
{
    if(ui_Music) lv_obj_del(ui_Music);

    // NULL screen variables
    ui_Music = NULL;
    ui_rlMusicList = NULL;
    ui_Container19 = NULL;
    ui_arcTime = NULL;
    ui_btnPrev = NULL;
    ui_btnPlay = NULL;
    ui_btnNext = NULL;
    ui_Container14 = NULL;
    ui_lblMusicTitle2 = NULL;
    ui_sldVolume = NULL;
    ui_lblMusicTitle = NULL;
    ui_btnBack2 = NULL;

}
