// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#ifndef UI_MUSIC_H
#define UI_MUSIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Music
extern void ui_Music_screen_init(void);
extern void ui_Music_screen_destroy(void);
extern void ui_event_Music(lv_event_t * e);
extern lv_obj_t * ui_Music;
extern void ui_event_rlMusicList(lv_event_t * e);
extern lv_obj_t * ui_rlMusicList;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_arcTime;
extern void ui_event_btnPrev(lv_event_t * e);
extern lv_obj_t * ui_btnPrev;
extern void ui_event_btnPlay(lv_event_t * e);
extern lv_obj_t * ui_btnPlay;
extern void ui_event_btnNext(lv_event_t * e);
extern lv_obj_t * ui_btnNext;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_lblMusicTitle2;
extern void ui_event_sldVolume(lv_event_t * e);
extern lv_obj_t * ui_sldVolume;
extern lv_obj_t * ui_lblMusicTitle;
extern void ui_event_btnBack2(lv_event_t * e);
extern lv_obj_t * ui_btnBack2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

