// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#include "../ui.h"

lv_obj_t * ui_Start = NULL;
lv_obj_t * ui_btnPlayer2Start = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_btnPlayer1Start = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_Start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        Start_OnLoaded(e);
    }
}

void ui_event_btnPlayer2Start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnPlayer2Start, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

void ui_event_btnPlayer1Start(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_btnPlayer1Start, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
    }
}

// build funtions

void ui_Start_screen_init(void)
{
    ui_Start = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Start, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Start, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Start, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_image_src(ui_Start, &ui_img_metal_table_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Start, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Start, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Start, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Start, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPlayer2Start = lv_button_create(ui_Start);
    lv_obj_set_width(ui_btnPlayer2Start, 210);
    lv_obj_set_height(ui_btnPlayer2Start, 100);
    lv_obj_set_x(ui_btnPlayer2Start, -47);
    lv_obj_set_y(ui_btnPlayer2Start, 92);
    lv_obj_set_align(ui_btnPlayer2Start, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnPlayer2Start, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnPlayer2Start, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPlayer2Start, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_btnPlayer2Start,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnPlayer2Start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPlayer2Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPlayer2Start, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnPlayer2Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnPlayer2Start, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_btnPlayer2Start);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -46);
    lv_obj_set_y(ui_Label3, 183);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "READY");
    lv_obj_remove_flag(ui_Label3, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPlayer1Start = lv_button_create(ui_Start);
    lv_obj_set_width(ui_btnPlayer1Start, 210);
    lv_obj_set_height(ui_btnPlayer1Start, 100);
    lv_obj_set_x(ui_btnPlayer1Start, -20);
    lv_obj_set_y(ui_btnPlayer1Start, 89);
    lv_obj_set_align(ui_btnPlayer1Start, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnPlayer1Start, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnPlayer1Start, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnPlayer1Start, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_btnPlayer1Start,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnPlayer1Start, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPlayer1Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPlayer1Start, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnPlayer1Start, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnPlayer1Start, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_btnPlayer1Start);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -46);
    lv_obj_set_y(ui_Label1, 183);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "READY");
    lv_obj_remove_flag(ui_Label1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnPlayer2Start, ui_event_btnPlayer2Start, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPlayer1Start, ui_event_btnPlayer1Start, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Start, ui_event_Start, LV_EVENT_ALL, NULL);

}

void ui_Start_screen_destroy(void)
{
    if(ui_Start) lv_obj_del(ui_Start);

    // NULL screen variables
    ui_Start = NULL;
    ui_btnPlayer2Start = NULL;
    ui_Label3 = NULL;
    ui_btnPlayer1Start = NULL;
    ui_Label1 = NULL;

}
