// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: Buckshot_Roulette_Project

#ifndef UI_START_H
#define UI_START_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Start
extern void ui_Start_screen_init(void);
extern void ui_Start_screen_destroy(void);
extern void ui_event_Start(lv_event_t * e);
extern lv_obj_t * ui_Start;
extern void ui_event_btnPlayer2Start(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer2Start;
extern lv_obj_t * ui_Label3;
extern void ui_event_btnPlayer1Start(lv_event_t * e);
extern lv_obj_t * ui_btnPlayer1Start;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

