// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifdef _WIN64
#include <iostream>
#endif
#include "ui.h"
#include "ui_events.h"
#include "../CommonData.h"
#include "../CommonLibrary.h"
#include "../CommonService.h"
#include "../Entity.h"

// Entity
static player::player_info_t* Player = nullptr;
static shotgun::shotgun_info_t Shotgun = { };

// Internal variable
static std::unordered_map<ITEM_TYPE, std::pair<lv_img_dsc_t, std::function<bool(player::player_info_t::player_slot_button_t&)>>> mapItemImg;
static std::vector<std::tuple<ITEM_TYPE, lv_img_dsc_t, lv_obj_t*>> listItemCardButton;
static ITEM_TYPE currentPickItem = ITEM_TYPE::MIN;
static bool itemUsingState = false;
static ITEM_TYPE itemUsingType = ITEM_TYPE::MIN;
static uint64_t lastShotgunTime = 0;
static PLAYER_TYPE latestPlayer = PLAYER_TYPE::PLAYER1;
static uint32_t tempMusicIndex = 0;

#pragma region Internal_functions
static void ResetPlayerTable()
{
    debug_println_func("Reset player table");

    for (auto& player : player::listPlayer)
    {
        player.Disable();
    }

    Shotgun.Disable();
}

static void ShowEjectedBullet()
{
    debug_println_func("Eject bullet");

    lv_obj_remove_flag(ui_imgEjectedBullet, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_imgTrashBullet, LV_OBJ_FLAG_HIDDEN);

    PlaySoundWrapper(SOUND_TYPE::DROP);
}

static void ShowTrashBullet()
{
    debug_println_func("Trash bullet");

    lv_obj_remove_flag(ui_imgTrashBullet, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_imgEjectedBullet, LV_OBJ_FLAG_HIDDEN);

    PlaySoundWrapper(SOUND_TYPE::DROP);
}

static void HideBulletInTable()
{
    debug_println_func("Hide bullet");

    lv_obj_add_flag(ui_imgTrashBullet, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(ui_imgEjectedBullet, LV_OBJ_FLAG_HIDDEN);
}
#pragma endregion

#include "../FSM.h"
#include "../Effect.h"

void Init()
{
    debug_println_func("Init");

    // Brightness
    Brightness.SetValue(100);
    lv_slider_set_value(ui_sldBrightness, Brightness.GetValue(), LV_ANIM_OFF);

    // Init image map
    mapItemImg = {
        { ITEM_TYPE::BEER           , { ui_img_beer_png           , EFFECT_FUNCTION_CALLBACK(BEER)            } },
        { ITEM_TYPE::BURNERPHONE    , { ui_img_burnerphone_png    , EFFECT_FUNCTION_CALLBACK(BURNERPHONE)     } },
        { ITEM_TYPE::CIGARETTE      , { ui_img_cigarette_png      , EFFECT_FUNCTION_CALLBACK(CIGARETTE)       } },
        { ITEM_TYPE::EXPIREDMEDICINE, { ui_img_expiredmedicine_png, EFFECT_FUNCTION_CALLBACK(EXPIREDMEDICINE) } },
        { ITEM_TYPE::HANDCUFFS      , { ui_img_handcuffs_png      , EFFECT_FUNCTION_CALLBACK(HANDCUFFS)       } },
        { ITEM_TYPE::HANDSAW        , { ui_img_handsaw_png        , EFFECT_FUNCTION_CALLBACK(HANDSAW)         } },
        { ITEM_TYPE::INVERTER       , { ui_img_inverter_png       , EFFECT_FUNCTION_CALLBACK(INVERTER)        } },
        { ITEM_TYPE::MAGNIFYINGGLASS, { ui_img_magnifyingglass_png, EFFECT_FUNCTION_CALLBACK(MAGNIFYINGGLASS) } },
        { ITEM_TYPE::ADRENALINE     , { ui_img_adrenaline_png     , EFFECT_FUNCTION_CALLBACK(ADRENALINE)      } },
    };

    // Init card info button
    listItemCardButton = {
        { ITEM_TYPE::BEER           , ui_img_beer_png           , ui_btnCard1 },
        { ITEM_TYPE::BURNERPHONE    , ui_img_burnerphone_png    , ui_btnCard2 },
        { ITEM_TYPE::CIGARETTE      , ui_img_cigarette_png      , ui_btnCard3 },
        { ITEM_TYPE::EXPIREDMEDICINE, ui_img_expiredmedicine_png, ui_btnCard4 },
        { ITEM_TYPE::HANDCUFFS      , ui_img_handcuffs_png      , ui_btnCard5 },
        { ITEM_TYPE::HANDSAW        , ui_img_handsaw_png        , ui_btnCard6 },
        { ITEM_TYPE::INVERTER       , ui_img_inverter_png       , ui_btnCard7 },
        { ITEM_TYPE::MAGNIFYINGGLASS, ui_img_magnifyingglass_png, ui_btnCard8 },
        { ITEM_TYPE::ADRENALINE     , ui_img_adrenaline_png     , ui_btnCard9 },
        { ITEM_TYPE::BLANK          , ui_img_cblank_png         , ui_btnCard10 },
        { ITEM_TYPE::LIVE           , ui_img_clive_png          , ui_btnCard11 },
        { ITEM_TYPE::NORMAL_CHARGE  , ui_img_cchargefront_png   , ui_btnCard12 },
        { ITEM_TYPE::FADED_CHARGE   , ui_img_cchargeback_png    , ui_btnCard13 },
    };

    // Init shotgun
    Shotgun.objInTable = ui_imgbtnShotgunInTable;
    Shotgun.objInside = ui_imgbtnShotgunInside;
    Shotgun.objHand = ui_imgShotgunInHand;
    Shotgun.objWndConfirm = ui_wndShotgunConfirm;
    Shotgun.objTrashBullet = ui_imgTrashBullet;
    Shotgun.mapBulletImg = {
        { BULLET_TYPE::MIN, ui_img_empty_bullet_png },
        { BULLET_TYPE::LIVE, ui_img_live_png },
        { BULLET_TYPE::BLANK, ui_img_blank_png },
    };
    Shotgun.listBulletImg = {
        ui_imgBullet1,
        ui_imgBullet2,
        ui_imgBullet3,
        ui_imgBullet4,
        ui_imgBullet5,
        ui_imgBullet6,
        ui_imgBullet7,
        ui_imgBullet8,
    };

    // Init player #1
    player::player_info_t player1 = { };
    player1.type = PLAYER_TYPE::PLAYER1;
    player1.table = ui_conPlayerLeft;
    player1.pickButton = ui_btnItemPick1;
    player1.confirmButton = ui_btnPlayerLeftConfirm;
    player1.gunfireEffect = ui_wndShotgunShotEffectLeft;
    player1.adrenalinefEffect = ui_wndAdrenalineEffectLeft;
    player1.listButtonInfo = {
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot1, ui_imgItemSlot1, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot2, ui_imgItemSlot2, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot3, ui_imgItemSlot3, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot4, ui_imgItemSlot4, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot5, ui_imgItemSlot5, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot6, ui_imgItemSlot6, { 0 } },
    };
    player1.listHPLevel1 = {
        ui_lblChargeBack1,
        ui_lblChargeBack2,
        ui_lblChargeBack3,
        ui_lblChargeBack4,
    };
    player1.listHPLevel2 = {
        ui_lblCharge1,
        ui_lblCharge2,
        ui_lblCharge3,
        ui_lblCharge4,
    };
    player1.hpLevel1 = MAX_HP;
    player1.hpLevel2 = MAX_HP;
    player1.angle = PLAYER1_ANGLE;

    // Init player #2
    player::player_info_t player2 = { };
    player2.type = PLAYER_TYPE::PLAYER2;
    player2.table = ui_conPlayerRight;
    player2.pickButton = ui_btnItemPick2;
    player2.confirmButton = ui_btnPlayerRightConfirm;
    player2.gunfireEffect = ui_wndShotgunShotEffectRight;
    player2.adrenalinefEffect = ui_wndAdrenalineEffectRight;
    player2.listButtonInfo = {
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot7, ui_imgItemSlot7, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot8, ui_imgItemSlot8, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot9, ui_imgItemSlot9, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot10, ui_imgItemSlot10, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot11, ui_imgItemSlot11, { 0 } },
        { PLAYER_TYPE::MIN, ITEM_TYPE::MIN, ui_btnItemSlot12, ui_imgItemSlot12, { 0 } },
    };
    player2.listHPLevel1 = {
        ui_lblChargeBack5,
        ui_lblChargeBack6,
        ui_lblChargeBack7,
        ui_lblChargeBack8,
    };
    player2.listHPLevel2 = {
        ui_lblCharge5,
        ui_lblCharge6,
        ui_lblCharge7,
        ui_lblCharge8,
    };
    player2.hpLevel1 = MAX_HP;
    player2.hpLevel2 = MAX_HP;
    player2.angle = PLAYER2_ANGLE;

    // Add player list
    player::listPlayer = { player1, player2 };

    // Init data
    CurrentState.SetValue(STATE_TYPE::STARTUP);
    MusicState.SetValue(MUSIC_STATE_TYPE::MIN);
    CurrentMusicIndex.SetValue(-1);

    PlaySoundWrapper(SOUND_TYPE::MIN);
}

void AutoUpdate()
{
#ifdef _WIN64 // Debug only
    // Debug change player
    if (debug_data::CurrentPlayer.GetState())
    {
        for (auto& player : player::listPlayer)
        {
            if (player.type == debug_data::CurrentPlayer.GetValue())
            {
                Player = &player;
                break;
            }
        }
    }
    if (debug_data::PlayerHP.GetState())
    {
        auto info = debug_data::PlayerHP.GetValue();

        for (auto& player : player::listPlayer)
        {
            if (player.type == std::get<0>(info))
            {
                if (std::get<1>(info) == 1)
                {
                    player.hpLevel1 = std::get<2>(info);
                }
                else if (std::get<1>(info) == 2)
                {
                    player.hpLevel2 = std::get<2>(info);
                }

                FSMTransit(STATE_TYPE::UPDATE_HP);

                break;
            }
        }
    }
    if (debug_data::SpecialCommand.GetState())
    {
        auto command = debug_data::SpecialCommand.GetValue();

        if (command == "bulletbox")
        {
            std::queue<BULLET_TYPE> tempQueue = Shotgun.queueBullet;

            debug_println("Bullet box:");
            while (!tempQueue.empty())
            {
                debug_println(map_BULLET_TYPE[tempQueue.front()]);
                tempQueue.pop();
            }
        }
        else if (command == "gettotalitem")
        {
            for (const auto& iPlayer : player::listPlayer)
            {
                debug_println(map_PLAYER_TYPE[iPlayer.type] + ": " + std::to_string(iPlayer.totalItemCount));
            }
        }

        debug_data::SpecialCommand.SetValue("");
    }
#endif

    // Pre-block check
    if (GuiBlockState.GetState())
    {
        if (GuiBlockState.GetValue())
        {
            debug_println_func("GUI pre-block");

            lv_obj_remove_flag(ui_wndBlock, LV_OBJ_FLAG_HIDDEN);
        }
        else
        {
            debug_println_func("GUI pre-unblock");

            lv_obj_add_flag(ui_wndBlock, LV_OBJ_FLAG_HIDDEN);
        }
    }

    FSM();

    if (MusicEnable.GetValue())
    {
        if ((MusicState.GetValue() == MUSIC_STATE_TYPE::RESUME) || (MusicState.GetValue() == MUSIC_STATE_TYPE::PLAY))
        {
            auto percent = GetCurrentMusicPercentWrapper();

            if (CurrentMusicPercent.GetState())
            {
                lv_arc_set_value(ui_arcTime, percent);
            }
        }
        else if (MusicState.GetValue() == MUSIC_STATE_TYPE::MSG_EOF)
        {
            MusicState.SetValue(MUSIC_STATE_TYPE::STOP);

            // Auto next music
            if (tempMusicIndex < Playlist.GetValue().size() - 1)
            {
                debug_println_func("Auto next music");

                auto currentMusicIndex = CurrentMusicIndex.GetValue();

                PlayMusicWrapper(Playlist.GetValue()[++currentMusicIndex]);
                lv_roller_set_selected(ui_rlMusicList, currentMusicIndex, LV_ANIM_OFF);

                MusicState.SetValue(MUSIC_STATE_TYPE::PLAY);
                CurrentMusicIndex.SetValue(currentMusicIndex);

                tempMusicIndex = currentMusicIndex;
            }
        }
    }

    if (MusicState.GetState())
    {
        auto state = MusicState.GetValue();

        debug_println_func("Music state: " + map_MUSIC_STATE_TYPE[state]);

        switch (state)
        {
        case MUSIC_STATE_TYPE::PLAY:
        case MUSIC_STATE_TYPE::RESUME:
        {
            if (state == MUSIC_STATE_TYPE::PLAY)
            {
                lv_label_set_text(ui_lblMusicTitle, Playlist.GetValue()[CurrentMusicIndex.GetValue()].c_str());
            }

            lv_obj_add_state(ui_btnPlay, LV_STATE_CHECKED);
        }
        break;
        case MUSIC_STATE_TYPE::PAUSE:
        case MUSIC_STATE_TYPE::STOP:
        {
            if (state == MUSIC_STATE_TYPE::STOP)
            {
                lv_label_set_text(ui_lblMusicTitle, "");
            }

            lv_obj_remove_state(ui_btnPlay, LV_STATE_CHECKED);
        }
        break;
        default:
            break;
        }
    }

    // Post-block check
    if (GuiBlockState.GetState())
    {
        if (GuiBlockState.GetValue())
        {
            debug_println_func("GUI post-block");

            lv_obj_remove_flag(ui_wndBlock, LV_OBJ_FLAG_HIDDEN);
        }
        else
        {
            debug_println_func("GUI post-unblock");

            lv_obj_add_flag(ui_wndBlock, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

void OnBrightnessChange(lv_event_t* e)
{
    Brightness.SetValue(lv_slider_get_value(ui_sldBrightness));
}

#pragma region Screen_events
void Start_OnLoaded(lv_event_t* e)
{

}

void Main_OnLoaded(lv_event_t* e)
{
    SetMusicStateWrapper(MUSIC_STATE_TYPE::STOP);

    MusicEnable.SetValue(false);

    if ((lv_obj_get_state(ui_btnSound) & LV_STATE_CHECKED) != LV_STATE_CHECKED)
    {
        SoundEnable.SetValue(true);
    }
}

void Music_OnLoaded(lv_event_t* e)
{
    // Get playlist
    if (!Playlist.GetValue().size())
    {
        debug_println_func("Update playlist, update volume");

        // Update playlist
        Playlist.SetValue(ExportListMusicFilesWrapper());
        CurrentMusicIndex.SetValue(lv_roller_get_selected(ui_rlMusicList));

        // Update volume slider
        lv_slider_set_range(ui_sldVolume, 0, GetMusicMaxVolumeWrapper());
        lv_slider_set_value(ui_sldVolume, DEFAULT_VOLUME, LV_ANIM_OFF);

        //Update playlist roller
        lv_roller_set_options(ui_rlMusicList, JoinString("\n", Playlist.GetValue()).c_str(), LV_ROLLER_MODE_NORMAL);

        SetMusicVolumeWrapper(DEFAULT_VOLUME);
    }

    // Update current index
    OnPlaylistChange(nullptr);

    SoundEnable.SetValue(false);
    MusicEnable.SetValue(true);

    // Reset music time
    lv_arc_set_value(ui_arcTime, 0);
}

void Info_OnLoaded(lv_event_t* e)
{
    debug_println_func("Info screen loaded");

    e->current_target = std::get<2>(listItemCardButton[0]);

    OnCardSelect(e);
}
#pragma endregion

#pragma region Component_events
void OnShotgunShot(lv_event_t* e)
{
    debug_println_func("Shotgun shot prepare");

    auto currentButton = (lv_obj_t*)(e->current_target);

    // Set target player
    for (auto& iPlayer : player::listPlayer)
    {
        if (currentButton == iPlayer.confirmButton)
        {
            Shotgun.targetPlayer = &iPlayer;
            break;
        }
    }

    debug_println_func("Confirm target: " + map_PLAYER_TYPE[Shotgun.targetPlayer->type]);

    lastShotgunTime = MILLISEC_GET;

    Shotgun.state = 0;

    FSMTransit(STATE_TYPE::SHOTGUN_SHOT);
}

void OnItemSelect(lv_event_t* e)
{
    debug_println_func("Item select");

    if (Player)
    {
        // Get current slot button
        auto currentButton = (lv_obj_t*)(e->current_target);

        if (CurrentState.GetValue() == STATE_TYPE::PLAYER_ITEM_ARRANGE)
        {
            debug_println_func("Item arrange");

            auto resultButtonInfo = std::find_if(Player->listButtonInfo.begin(), Player->listButtonInfo.end(),
                [currentButton](const decltype(Player->listButtonInfo.front())& item) {
                    // Button has no assigned image
                    return ((item.button == currentButton) && (item.image.data_size == 0));
                });

            if (resultButtonInfo != Player->listButtonInfo.end())
            {
                auto& buttonInfo = (*resultButtonInfo); // Get button info
                auto imgCardReview = lv_image_get_src(ui_imgCardReview); // Get image from card review

                debug_println_func("Pick: " + map_ITEM_TYPE[currentPickItem]);

                // Assign button
                buttonInfo.Assign(Player->type, currentPickItem, imgCardReview);

                // Update item count
                Player->pickItemCount++;
                Player->totalItemCount++;

                // Hide card review
                lv_obj_add_flag(ui_imgCardReview, LV_OBJ_FLAG_HIDDEN);

                FSMTransit(STATE_TYPE::PICK);
            }
        }
        else if (CurrentState.GetValue() == STATE_TYPE::ACTION_ITEM)
        {
            debug_println_func("Item action");

            if (itemUsingType == ITEM_TYPE::ADRENALINE)
            {
                debug_println_func("Current using is ADRENALINE");

                for (auto& iPlayer : player::listPlayer)
                {
                    auto resultButtonInfo = std::find_if(iPlayer.listButtonInfo.begin(), iPlayer.listButtonInfo.end(),
                        [currentButton](const decltype(iPlayer.listButtonInfo.front())& item) {
                            // Button has assigned image
                            return ((item.button == currentButton) && (item.image.data_size > 0));
                        });

                    if (resultButtonInfo != iPlayer.listButtonInfo.end())
                    {
                        debug_println_func("Button found");

                        auto& buttonInfo = (*resultButtonInfo); // Get button info

                        if ((buttonInfo.playerType != Player->type) && (buttonInfo.itemType != ITEM_TYPE::ADRENALINE) && (!itemUsingState))
                        {
                            debug_println_func("Use: " + map_ITEM_TYPE[buttonInfo.itemType]);
                            debug_println_func("From: " + map_PLAYER_TYPE[buttonInfo.playerType]);

                            auto itemType = buttonInfo.itemType;
                            itemUsingState = true; // Block other action

                            if (mapItemImg[itemType].second(buttonInfo)) // Call item effect
                            {
                                debug_println_func("Using done");

                                itemUsingType = itemType;

                                iPlayer.totalItemCount--;

                                player::DisableAllPlayerTableExcept(*Player);

                                // Hide effect
                                lv_obj_add_flag(ui_wndAdrenalineEffect, LV_OBJ_FLAG_HIDDEN);
                                lv_obj_add_flag(Player->adrenalinefEffect, LV_OBJ_FLAG_HIDDEN);

                                Shotgun.Enable();
                            }
                        }

                        break;
                    }
                }
            }
            else
            {
                debug_println_func("Current using is none");

                auto resultButtonInfo = std::find_if(Player->listButtonInfo.begin(), Player->listButtonInfo.end(),
                    [currentButton](const decltype(Player->listButtonInfo.front())& item) {
                        // Button has assigned image
                        return ((item.button == currentButton) && (item.image.data_size > 0));
                    });

                if (resultButtonInfo != Player->listButtonInfo.end())
                {
                    debug_println_func("Button found");

                    auto& buttonInfo = (*resultButtonInfo); // Get button info

                    if (!itemUsingState)
                    {
                        debug_println_func("Use: " + map_ITEM_TYPE[buttonInfo.itemType]);

                        itemUsingType = buttonInfo.itemType; // Update item using

                        itemUsingState = true; // Block other action
                        mapItemImg[buttonInfo.itemType].second(buttonInfo); // Call item effect

                        Player->totalItemCount--;

                        debug_println_func("Using done");
                    }
                }
            }
        }
    }
}

void OnShotgunSelect(lv_event_t* e)
{
    debug_println_func("Shotgun select");

    if (CurrentState.GetValue() == STATE_TYPE::LOAD_SHELL)
    {
        debug_println_func("Shell loaded");

        // Show bullet box cover
        lv_obj_remove_flag(ui_imgBulletBoxCover, LV_OBJ_FLAG_HIDDEN);

        // Hide message
        lv_label_set_text(ui_lblMessage, "");

        for (const auto& item : Shotgun.listBullet)
        {
            PlaySoundWrapper(SOUND_TYPE::DROP);
#ifdef _WIN64
            ::Sleep(500);
#else
            delay(500);
#endif
        }

        PlaySoundWrapper(SOUND_TYPE::LOAD_SHELL);

        FSMTransit(STATE_TYPE::ACTION_TURN);
    }
    else if (CurrentState.GetValue() == STATE_TYPE::ACTION_ITEM)
    {
        debug_println_func("Show shotgun in hand");

        Shotgun.ShowInHand(*Player);
    }
}

void OnItemPick(lv_event_t* e)
{
    debug_println_func("Pick item");

#ifdef _WIN64
    if ((uint8_t)debug_data::CurrentItemType.GetValue() > 0)
    {
        currentPickItem = debug_data::CurrentItemType.GetValue();
    }
    else
    {
        currentPickItem = RandomRangeEnum(ITEM_TYPE::MIN, ITEM_TYPE::MAX);
    }

    debug_data::CurrentItemType.SetValue(ITEM_TYPE::MIN);
#else
    currentPickItem = RandomRangeEnum(ITEM_TYPE::MIN, ITEM_TYPE::MAX);
#endif

    // Show and set image to card review
    lv_obj_remove_flag(ui_imgCardReview, LV_OBJ_FLAG_HIDDEN);
    lv_image_set_src(ui_imgCardReview, &mapItemImg[currentPickItem].first);

    if (Player)
    {
        Player->DisablePickButton();

        if ((Player->pickItemCount == MAX_PICK_ITEM_PER_ROUND) || (Player->totalItemCount == MAX_ITEM_NUM))
        {
            ResetPlayerTable();

            // Set message
            if (Player->totalItemCount == MAX_ITEM_NUM)
            {
                debug_println_func(MSG_OUT_OF_SPACE);

                lv_label_set_text(ui_lblMessage, MSG_OUT_OF_SPACE);
            }
            else if (Player->pickItemCount == MAX_PICK_ITEM_PER_ROUND)
            {
                debug_println_func(MSG_END_TURN);

                lv_label_set_text(ui_lblMessage, MSG_END_TURN);
            }

            // Hide card review
            lv_obj_add_flag(ui_imgCardReview, LV_OBJ_FLAG_HIDDEN);

            // Reset pick item count, keep total count
            Player->pickItemCount = 0;
            Player->isPickComplete = true;

            // Show delayed message
            DelayCallback(MAKE_DELAY_CB{
                // Hide message
                lv_label_set_text(ui_lblMessage, "");

                FSMTransit(STATE_TYPE::PLAYER_NEXT);
                }, nullptr, WAIT_TIME);
        }
        else
        {
            PlaySoundWrapper(SOUND_TYPE::PICK);

            FSMTransit(STATE_TYPE::PLAYER_ITEM_ARRANGE);
        }
    }
}

void OnShotgunInside(lv_event_t* e)
{
    auto eventCode = lv_event_get_code(e);

    if (eventCode == LV_EVENT_PRESSED)
    {
        if (itemUsingType == ITEM_TYPE::MAGNIFYINGGLASS)
        {
            debug_println_func("Use Magnifying Glass");

            // Show first bullet
            lv_image_set_src(ui_imgShotgunBullet, &Shotgun.mapBulletImg[Shotgun.queueBullet.front()]);
        }
        else if (itemUsingType == ITEM_TYPE::BURNERPHONE)
        {
            debug_println_func("Use Burner Phone");

            // Show message
            lv_obj_remove_flag(ui_lblMessageInside, LV_OBJ_FLAG_HIDDEN);
        }

        PlaySoundWrapper(SOUND_TYPE::LOAD_SHELL);
    }
    else
    {
        debug_println_func("Hide shotgun inside");

        // Reset bullet slot
        lv_image_set_src(ui_imgShotgunBullet, &Shotgun.mapBulletImg[BULLET_TYPE::MIN]);

        // Hide shotgun inside
        lv_obj_add_flag(Shotgun.objInside, LV_OBJ_FLAG_HIDDEN);

        // Hide message
        lv_obj_add_flag(ui_lblMessageInside, LV_OBJ_FLAG_HIDDEN);

        itemUsingState = false;
    }
}

void OnCardSelect(lv_event_t* e)
{
    debug_println_func("Card select");

    auto currentButton = (lv_obj_t*)(e->current_target);

    auto resultButtonInfo = std::find_if(listItemCardButton.begin(), listItemCardButton.end(),
        [currentButton](const decltype(listItemCardButton.front())& item) {
            return (std::get<2>(item) == currentButton);
        });

    if (resultButtonInfo != listItemCardButton.end())
    {
        const auto& item = *resultButtonInfo;

        debug_println_func("Select " + map_ITEM_TYPE[std::get<0>(item)]);

        // Set text
        lv_label_set_text(ui_lblCardInfoTitle, mapCardInfoName[std::get<0>(item)].c_str());
        lv_label_set_text(ui_lblUsageInfo, JoinString("\n", mapCardInfoDesc[std::get<0>(item)].usageLines).c_str());
        lv_label_set_text(ui_lblStrategyInfo, JoinString("\n", mapCardInfoDesc[std::get<0>(item)].strategyLines).c_str());

        // Set image
        lv_image_set_src(ui_imgInfoCardReview, &std::get<1>(item));

        PlaySoundWrapper(SOUND_TYPE::PICK);
    }
}

void OnAdrenalineCancel(lv_event_t* e)
{
    debug_println_func("Adrenaline cancel");

    itemUsingType = ITEM_TYPE::MIN;

    player::DisableAllPlayerTableExcept(*Player);

    // Hide effect
    lv_obj_add_flag(ui_wndAdrenalineEffect, LV_OBJ_FLAG_HIDDEN);
    lv_obj_add_flag(Player->adrenalinefEffect, LV_OBJ_FLAG_HIDDEN);

    itemUsingState = false; // Unblock

    Shotgun.Enable();

    PlaySoundWrapper(SOUND_TYPE::BREAK);
}

void OnButtonSound(lv_event_t* e)
{
    if ((lv_obj_get_state((lv_obj_t*)(e->current_target)) & LV_STATE_CHECKED) == LV_STATE_CHECKED)
    {
        SoundEnable.SetValue(false);
    }
    else
    {
        SoundEnable.SetValue(true);
    }
}

void OnMusicControl(lv_event_t* e)
{
    auto currentMusicIndex = CurrentMusicIndex.GetValue();
    auto playlist = Playlist.GetValue();

    if (e->current_target == ui_btnPlay)
    {
        if ((MusicState.GetValue() == MUSIC_STATE_TYPE::STOP) || (tempMusicIndex != CurrentMusicIndex.GetValue()))
        {
            debug_println_func("Play music");

            PlayMusicWrapper(playlist[tempMusicIndex]);

            MusicState.SetValue(MUSIC_STATE_TYPE::STOP);
            MusicState.SetValue(MUSIC_STATE_TYPE::PLAY);

            if (tempMusicIndex != CurrentMusicIndex.GetValue())
            {
                currentMusicIndex = tempMusicIndex;
            }
        }
        else if ((lv_obj_get_state(ui_btnPlay) & LV_STATE_CHECKED) == LV_STATE_CHECKED)
        {
            debug_println_func("Resume music");

            SetMusicStateWrapper(MUSIC_STATE_TYPE::RESUME);
        }
        else
        {
            debug_println_func("Pause music");

            SetMusicStateWrapper(MUSIC_STATE_TYPE::PAUSE);
        }
    }
    else if (e->current_target == ui_btnPrev)
    {
        if (tempMusicIndex > 0)
        {
            debug_println_func("Prev music");

            PlayMusicWrapper(playlist[--tempMusicIndex]);
            lv_roller_set_selected(ui_rlMusicList, tempMusicIndex, LV_ANIM_OFF);

            MusicState.SetValue(MUSIC_STATE_TYPE::STOP);
            MusicState.SetValue(MUSIC_STATE_TYPE::PLAY);

            currentMusicIndex = tempMusicIndex;
        }

    }
    else if (e->current_target == ui_btnNext)
    {
        if (tempMusicIndex < Playlist.GetValue().size() - 1)
        {
            debug_println_func("Next music");

            PlayMusicWrapper(playlist[++tempMusicIndex]);
            lv_roller_set_selected(ui_rlMusicList, tempMusicIndex, LV_ANIM_OFF);

            MusicState.SetValue(MUSIC_STATE_TYPE::STOP);
            MusicState.SetValue(MUSIC_STATE_TYPE::PLAY);

            currentMusicIndex = tempMusicIndex;
        }
    }

    CurrentMusicIndex.SetValue(currentMusicIndex);
}

void OnVolumeChange(lv_event_t* e)
{
    SetMusicVolumeWrapper(lv_slider_get_value(ui_sldVolume));
}

void OnPlaylistChange(lv_event_t* e)
{
    tempMusicIndex = lv_roller_get_selected(ui_rlMusicList);
}
#pragma endregion
