// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#ifndef UI_KEYBOARD_H
#define UI_KEYBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Keyboard
extern void ui_Keyboard_screen_init(void);
extern void ui_Keyboard_screen_destroy(void);
extern void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_lblKeyboardTitle;
extern lv_obj_t * ui_Con1;
extern lv_obj_t * ui_txtKeyboardInput;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_txtKeyboardTempInput;
extern lv_obj_t * ui_pnlNumpad;
extern void ui_event_btnKeyboardKey1(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey1;
extern lv_obj_t * ui_Label25;
extern void ui_event_btnKeyboardKey2(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey2;
extern lv_obj_t * ui_Label27;
extern void ui_event_btnKeyboardKey3(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey3;
extern lv_obj_t * ui_Label28;
extern void ui_event_btnKeyboardKey4(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey4;
extern lv_obj_t * ui_Label29;
extern void ui_event_btnKeyboardKey5(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey5;
extern lv_obj_t * ui_Label30;
extern void ui_event_btnKeyboardKey6(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey6;
extern lv_obj_t * ui_Label31;
extern void ui_event_btnKeyboardKey7(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey7;
extern lv_obj_t * ui_Label32;
extern void ui_event_btnKeyboardKey8(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey8;
extern lv_obj_t * ui_Label33;
extern void ui_event_btnKeyboardKey9(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey9;
extern lv_obj_t * ui_Label36;
extern void ui_event_btnKeyboardKey0(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKey0;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Image4;
extern void ui_event_btnKeyboardKeyShift(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKeyShift;
extern void ui_event_btnKeyboardKeyBackspace(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardKeyBackspace;
extern lv_obj_t * ui_Container1;
extern void ui_event_btnKeyboardCancel(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardCancel;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label34;
extern void ui_event_btnKeyboardOK(lv_event_t * e);
extern lv_obj_t * ui_btnKeyboardOK;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Label35;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

