// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#ifndef UI_KEYBOARD_H
#define UI_KEYBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Keyboard
extern void ui_Keyboard_screen_init(void);
extern void ui_Keyboard_screen_destroy(void);
extern void ui_event_Keyboard(lv_event_t * e);
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_label24;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label38;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_btnPlayer2Start18;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_btnPlayer2Start19;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_btnPlayer2Start20;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_btnPlayer2Start21;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_btnPlayer2Start22;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_btnPlayer2Start23;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_btnPlayer2Start24;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_btnPlayer2Start27;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_btnPlayer2Start28;
extern lv_obj_t * ui_Label36;
extern lv_obj_t * ui_btnPlayer2Start29;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_btnPlayer2Start30;
extern lv_obj_t * ui_btnPlayer2Start31;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_btnPlayer2Start25;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_btnPlayer2Start26;
extern lv_obj_t * ui_Label35;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

