// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#ifndef UI_MAIN_H
#define UI_MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main
extern void ui_Main_screen_init(void);
extern void ui_Main_screen_destroy(void);
extern void ui_event_Main(lv_event_t * e);
extern lv_obj_t * ui_Main;
extern void ui_event_btnNewVideo(lv_event_t * e);
extern lv_obj_t * ui_btnNewVideo;
extern void ui_event_btnCloseVideo(lv_event_t * e);
extern lv_obj_t * ui_btnCloseVideo;
extern void ui_event_btnFastRewind(lv_event_t * e);
extern lv_obj_t * ui_btnFastRewind;
extern void ui_event_btnFastForward(lv_event_t * e);
extern lv_obj_t * ui_btnFastForward;
extern void ui_event_btnFolderList(lv_event_t * e);
extern lv_obj_t * ui_btnFolderList;
extern void ui_event_btnSystemSetting(lv_event_t * e);
extern lv_obj_t * ui_btnSystemSetting;
extern lv_obj_t * ui_wndReview;
extern lv_obj_t * ui_Panel2;
extern void ui_event_btnRec(lv_event_t * e);
extern lv_obj_t * ui_btnRec;
extern void ui_event_btnPause(lv_event_t * e);
extern lv_obj_t * ui_btnPause;
extern void ui_event_btnPlay(lv_event_t * e);
extern lv_obj_t * ui_btnPlay;
extern void ui_event_btnStop(lv_event_t * e);
extern lv_obj_t * ui_btnStop;
extern void ui_event_btnSound(lv_event_t * e);
extern lv_obj_t * ui_btnSound;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_lblDate;
extern lv_obj_t * ui_lblTime;
extern lv_obj_t * ui_lblStorage;
extern lv_obj_t * ui_Image1;
extern void ui_event_btnStatusDisplay(lv_event_t * e);
extern lv_obj_t * ui_btnStatusDisplay;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

