// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#include "../ui.h"

lv_obj_t * ui_Main = NULL;
lv_obj_t * ui_btnNewVideo = NULL;
lv_obj_t * ui_btnCloseVideo = NULL;
lv_obj_t * ui_btnFastRewind = NULL;
lv_obj_t * ui_btnFastForward = NULL;
lv_obj_t * ui_btnFolderList = NULL;
lv_obj_t * ui_btnSystemSetting = NULL;
lv_obj_t * ui_wndReview = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_btnRec = NULL;
lv_obj_t * ui_btnPause = NULL;
lv_obj_t * ui_btnPlay = NULL;
lv_obj_t * ui_btnStop = NULL;
lv_obj_t * ui_btnSound = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_lblDate = NULL;
lv_obj_t * ui_lblTime = NULL;
lv_obj_t * ui_lblStorage = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_btnStatusDisplay = NULL;
lv_obj_t * ui_Label10 = NULL;
// event funtions
void ui_event_Main(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        CommonOnLoaded(e);
    }
}

void ui_event_btnNewVideo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnCloseVideo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnFastRewind(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnFastForward(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnFolderList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnSystemSetting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRec(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnPause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnSound(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnStatusDisplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

// build funtions

void ui_Main_screen_init(void)
{
    ui_Main = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_Main, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Main, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnNewVideo = lv_button_create(ui_Main);
    lv_obj_set_width(ui_btnNewVideo, 260);
    lv_obj_set_height(ui_btnNewVideo, 80);
    lv_obj_set_x(ui_btnNewVideo, -101);
    lv_obj_set_y(ui_btnNewVideo, 104);
    lv_obj_set_align(ui_btnNewVideo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnNewVideo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnNewVideo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnNewVideo, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnNewVideo, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnNewVideo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnNewVideo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnNewVideo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnNewVideo, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnNewVideo, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnNewVideo, &ui_img_new_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnNewVideo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnNewVideo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnNewVideo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnCloseVideo = lv_button_create(ui_Main);
    lv_obj_set_width(ui_btnCloseVideo, 260);
    lv_obj_set_height(ui_btnCloseVideo, 80);
    lv_obj_set_x(ui_btnCloseVideo, -47);
    lv_obj_set_y(ui_btnCloseVideo, 92);
    lv_obj_set_align(ui_btnCloseVideo, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnCloseVideo, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnCloseVideo, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnCloseVideo,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnCloseVideo, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnCloseVideo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnCloseVideo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnCloseVideo, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnCloseVideo, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnCloseVideo, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnCloseVideo, &ui_img_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnCloseVideo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnCloseVideo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnCloseVideo, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnFastRewind = lv_button_create(ui_Main);
    lv_obj_set_width(ui_btnFastRewind, 80);
    lv_obj_set_height(ui_btnFastRewind, 80);
    lv_obj_set_x(ui_btnFastRewind, -47);
    lv_obj_set_y(ui_btnFastRewind, 92);
    lv_obj_set_align(ui_btnFastRewind, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnFastRewind, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnFastRewind, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnFastRewind,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnFastRewind, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnFastRewind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnFastRewind, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnFastRewind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnFastRewind, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnFastRewind, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnFastRewind, &ui_img_fast_rewind_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnFastRewind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnFastRewind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnFastRewind, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnFastForward = lv_button_create(ui_Main);
    lv_obj_set_width(ui_btnFastForward, 80);
    lv_obj_set_height(ui_btnFastForward, 80);
    lv_obj_set_x(ui_btnFastForward, -47);
    lv_obj_set_y(ui_btnFastForward, 92);
    lv_obj_set_align(ui_btnFastForward, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnFastForward, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnFastForward, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnFastForward,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnFastForward, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnFastForward, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnFastForward, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnFastForward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnFastForward, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnFastForward, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnFastForward, &ui_img_fast_forward_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnFastForward, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnFastForward, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnFastForward, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnFolderList = lv_button_create(ui_Main);
    lv_obj_set_width(ui_btnFolderList, 265);
    lv_obj_set_height(ui_btnFolderList, 80);
    lv_obj_set_x(ui_btnFolderList, -47);
    lv_obj_set_y(ui_btnFolderList, 92);
    lv_obj_set_align(ui_btnFolderList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnFolderList, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnFolderList, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnFolderList,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnFolderList, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnFolderList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnFolderList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnFolderList, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnFolderList, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnFolderList, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnFolderList, &ui_img_list_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnFolderList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnFolderList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnFolderList, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSystemSetting = lv_button_create(ui_Main);
    lv_obj_set_width(ui_btnSystemSetting, 265);
    lv_obj_set_height(ui_btnSystemSetting, 80);
    lv_obj_set_x(ui_btnSystemSetting, -47);
    lv_obj_set_y(ui_btnSystemSetting, 92);
    lv_obj_set_align(ui_btnSystemSetting, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnSystemSetting, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnSystemSetting, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnSystemSetting,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnSystemSetting, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSystemSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnSystemSetting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnSystemSetting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnSystemSetting, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnSystemSetting, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnSystemSetting, &ui_img_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSystemSetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSystemSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSystemSetting, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wndReview = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_wndReview);
    lv_obj_set_width(ui_wndReview, 1150);
    lv_obj_set_height(ui_wndReview, 560);
    lv_obj_set_x(ui_wndReview, -419);
    lv_obj_set_y(ui_wndReview, -71);
    lv_obj_set_align(ui_wndReview, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wndReview, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_wndReview, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_wndReview, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wndReview, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Panel2, 105);
    lv_obj_set_height(ui_Panel2, 560);
    lv_obj_set_x(ui_Panel2, -202);
    lv_obj_set_y(ui_Panel2, 196);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRec = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_btnRec, 80);
    lv_obj_set_height(ui_btnRec, 80);
    lv_obj_set_x(ui_btnRec, -47);
    lv_obj_set_y(ui_btnRec, 92);
    lv_obj_set_align(ui_btnRec, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRec, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRec, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRec, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRec, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRec, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRec, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRec, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRec, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRec, &ui_img_record_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRec, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRec, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRec, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPause = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_btnPause, 80);
    lv_obj_set_height(ui_btnPause, 80);
    lv_obj_set_x(ui_btnPause, -47);
    lv_obj_set_y(ui_btnPause, 92);
    lv_obj_set_align(ui_btnPause, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnPause, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnPause, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnPause, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnPause, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnPause, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnPause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnPause, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnPause, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnPause, &ui_img_pause_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnPause, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnPlay = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_btnPlay, 80);
    lv_obj_set_height(ui_btnPlay, 80);
    lv_obj_set_x(ui_btnPlay, -47);
    lv_obj_set_y(ui_btnPlay, 92);
    lv_obj_set_align(ui_btnPlay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnPlay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnPlay, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnPlay, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnPlay, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnPlay, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnPlay, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnPlay, &ui_img_play_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnPlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnPlay, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnStop = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_btnStop, 80);
    lv_obj_set_height(ui_btnStop, 80);
    lv_obj_set_x(ui_btnStop, -47);
    lv_obj_set_y(ui_btnStop, 92);
    lv_obj_set_align(ui_btnStop, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnStop, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnStop, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnStop, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnStop, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnStop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnStop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnStop, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnStop, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnStop, &ui_img_stop_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnStop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnStop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnSound = lv_button_create(ui_Panel2);
    lv_obj_set_width(ui_btnSound, 80);
    lv_obj_set_height(ui_btnSound, 80);
    lv_obj_set_x(ui_btnSound, -47);
    lv_obj_set_y(ui_btnSound, 92);
    lv_obj_set_align(ui_btnSound, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnSound, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnSound, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnSound, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_btnSound, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnSound, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnSound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnSound, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnSound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnSound, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnSound, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnSound, &ui_img_brand_awareness_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnSound, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnSound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnSound, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnSound, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnSound, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_btnSound, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_src(ui_btnSound, &ui_img_no_sound_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Container3 = lv_obj_create(ui_Main);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 1260);
    lv_obj_set_height(ui_Container3, 90);
    lv_obj_set_x(ui_Container3, 547);
    lv_obj_set_y(ui_Container3, 215);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_lblDate = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblDate, 280);
    lv_obj_set_height(ui_lblDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblDate, -46);
    lv_obj_set_y(ui_lblDate, 183);
    lv_obj_set_align(ui_lblDate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblDate, "00/00/0000");
    lv_obj_remove_flag(ui_lblDate, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblDate, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblDate, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblDate, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblTime = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblTime, 210);
    lv_obj_set_height(ui_lblTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblTime, -46);
    lv_obj_set_y(ui_lblTime, 183);
    lv_obj_set_align(ui_lblTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblTime, "00:00:00");
    lv_obj_remove_flag(ui_lblTime, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblTime, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblTime, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblStorage = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_lblStorage, 330);
    lv_obj_set_height(ui_lblStorage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblStorage, -46);
    lv_obj_set_y(ui_lblStorage, 183);
    lv_obj_set_align(ui_lblStorage, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblStorage, "000.0 GB free");
    lv_obj_remove_flag(ui_lblStorage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblStorage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblStorage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblStorage, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblStorage, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Container3);
    lv_image_set_src(ui_Image1, &ui_img_storage_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 337);
    lv_obj_set_y(ui_Image1, 340);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_Image1, LV_IMAGE_ALIGN_LEFT_MID);

    ui_btnStatusDisplay = lv_button_create(ui_Container3);
    lv_obj_set_width(ui_btnStatusDisplay, 365);
    lv_obj_set_height(ui_btnStatusDisplay, 80);
    lv_obj_set_x(ui_btnStatusDisplay, -47);
    lv_obj_set_y(ui_btnStatusDisplay, 92);
    lv_obj_set_align(ui_btnStatusDisplay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnStatusDisplay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnStatusDisplay, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnStatusDisplay,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnStatusDisplay, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnStatusDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnStatusDisplay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnStatusDisplay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnStatusDisplay, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnStatusDisplay, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnStatusDisplay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnStatusDisplay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnStatusDisplay, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_btnStatusDisplay);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -46);
    lv_obj_set_y(ui_Label10, 183);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Status display");
    lv_obj_remove_flag(ui_Label10, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnNewVideo, ui_event_btnNewVideo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnCloseVideo, ui_event_btnCloseVideo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFastRewind, ui_event_btnFastRewind, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFastForward, ui_event_btnFastForward, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnFolderList, ui_event_btnFolderList, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSystemSetting, ui_event_btnSystemSetting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRec, ui_event_btnRec, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPause, ui_event_btnPause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnPlay, ui_event_btnPlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnStop, ui_event_btnStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnSound, ui_event_btnSound, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnStatusDisplay, ui_event_btnStatusDisplay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Main, ui_event_Main, LV_EVENT_ALL, NULL);

}

void ui_Main_screen_destroy(void)
{
    if(ui_Main) lv_obj_del(ui_Main);

    // NULL screen variables
    ui_Main = NULL;
    ui_btnNewVideo = NULL;
    ui_btnCloseVideo = NULL;
    ui_btnFastRewind = NULL;
    ui_btnFastForward = NULL;
    ui_btnFolderList = NULL;
    ui_btnSystemSetting = NULL;
    ui_wndReview = NULL;
    ui_Panel2 = NULL;
    ui_btnRec = NULL;
    ui_btnPause = NULL;
    ui_btnPlay = NULL;
    ui_btnStop = NULL;
    ui_btnSound = NULL;
    ui_Container3 = NULL;
    ui_lblDate = NULL;
    ui_lblTime = NULL;
    ui_lblStorage = NULL;
    ui_Image1 = NULL;
    ui_btnStatusDisplay = NULL;
    ui_Label10 = NULL;

}
