// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#include "../ui.h"

lv_obj_t * ui_RecordList = NULL;
lv_obj_t * ui_lblVideoSearch = NULL;
lv_obj_t * ui_btnVideoSearch = NULL;
lv_obj_t * ui_dropVideoFilter = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_conRecordListList = NULL;
lv_obj_t * ui_imgRecordListVideo1 = NULL;
lv_obj_t * ui_imgRecordListVideo2 = NULL;
lv_obj_t * ui_imgRecordListVideo3 = NULL;
lv_obj_t * ui_imgRecordListVideo4 = NULL;
lv_obj_t * ui_imgRecordListVideo5 = NULL;
lv_obj_t * ui_imgRecordListVideo6 = NULL;
lv_obj_t * ui_imgRecordListVideo7 = NULL;
lv_obj_t * ui_imgRecordListVideo8 = NULL;
lv_obj_t * ui_imgRecordListVideo9 = NULL;
lv_obj_t * ui_btnRecordListPrePage = NULL;
lv_obj_t * ui_btnRecordListPlayPause = NULL;
lv_obj_t * ui_btnRecordListNextPage = NULL;
lv_obj_t * ui_lblRecordListPageInfo = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_lblInfoVideoDateTime = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_lblInfoVideoEvent = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_lblInfoVideoName = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_lblInfoVideoCategory = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_lblInfoVideDesc = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_lblInfoVideoAuthor = NULL;
lv_obj_t * ui_btnRecordListDelete = NULL;
lv_obj_t * ui_btnRecordListTransfer = NULL;
lv_obj_t * ui_dropPortableMemory = NULL;
lv_obj_t * ui_btnRecordListBack = NULL;
// event funtions
void ui_event_RecordList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        CommonOnLoaded(e);
    }
}

void ui_event_btnVideoSearch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_dropVideoFilter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CommonButtonOnValueChange(e);
    }
}

void ui_event_imgRecordListVideo1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_imgRecordListVideo2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_imgRecordListVideo3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_imgRecordListVideo4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_imgRecordListVideo5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_imgRecordListVideo6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_imgRecordListVideo7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_imgRecordListVideo8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_imgRecordListVideo9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRecordListPrePage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRecordListPlayPause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRecordListNextPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRecordListDelete(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRecordListTransfer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_dropPortableMemory(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CommonButtonOnValueChange(e);
    }
}

void ui_event_btnRecordListBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

// build funtions

void ui_RecordList_screen_init(void)
{
    ui_RecordList = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RecordList, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_RecordList, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_RecordList, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RecordList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVideoSearch = lv_label_create(ui_RecordList);
    lv_obj_set_width(ui_lblVideoSearch, 735);
    lv_obj_set_height(ui_lblVideoSearch, 80);
    lv_obj_set_x(ui_lblVideoSearch, 75);
    lv_obj_set_y(ui_lblVideoSearch, 184);
    lv_obj_set_align(ui_lblVideoSearch, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVideoSearch, "");
    lv_obj_remove_flag(ui_lblVideoSearch,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblVideoSearch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblVideoSearch, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblVideoSearch, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnVideoSearch = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnVideoSearch, 80);
    lv_obj_set_height(ui_btnVideoSearch, 80);
    lv_obj_set_x(ui_btnVideoSearch, -47);
    lv_obj_set_y(ui_btnVideoSearch, 92);
    lv_obj_set_align(ui_btnVideoSearch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnVideoSearch, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnVideoSearch, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnVideoSearch,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnVideoSearch, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnVideoSearch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnVideoSearch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnVideoSearch, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnVideoSearch, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnVideoSearch, &ui_img_search_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnVideoSearch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnVideoSearch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropVideoFilter = lv_dropdown_create(ui_RecordList);
    lv_dropdown_set_options(ui_dropVideoFilter, "--All video--\nEvent\nVideo name\nCategory\nDescription\nAuthor");
    lv_dropdown_set_selected_highlight(ui_dropVideoFilter, false);
    lv_obj_set_width(ui_dropVideoFilter, 360);
    lv_obj_set_height(ui_dropVideoFilter, 80);
    lv_obj_set_x(ui_dropVideoFilter, -194);
    lv_obj_set_y(ui_dropVideoFilter, -313);
    lv_obj_set_align(ui_dropVideoFilter, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dropVideoFilter,
                       LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_dropVideoFilter, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_dropVideoFilter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dropVideoFilter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dropVideoFilter, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dropVideoFilter, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dropVideoFilter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dropVideoFilter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_dropVideoFilter), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_dropVideoFilter), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_dropVideoFilter), &lv_font_montserrat_46,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_dropVideoFilter), lv_color_hex(0x424242),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_dropVideoFilter), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_RecordList);
    lv_image_set_src(ui_Image2, &ui_img_filter_png);
    lv_obj_set_width(ui_Image2, 55);
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 599);
    lv_obj_set_y(ui_Image2, -234);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_RecordList);
    lv_obj_set_width(ui_Panel3, 1265);
    lv_obj_set_height(ui_Panel3, 665);
    lv_obj_set_x(ui_Panel3, -204);
    lv_obj_set_y(ui_Panel3, 194);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 750);
    lv_obj_set_height(ui_Container5, 665);
    lv_obj_set_x(ui_Container5, -418);
    lv_obj_set_y(ui_Container5, -71);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conRecordListList = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_conRecordListList);
    lv_obj_set_width(ui_conRecordListList, 750);
    lv_obj_set_height(ui_conRecordListList, 560);
    lv_obj_set_align(ui_conRecordListList, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conRecordListList, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_conRecordListList, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_conRecordListList,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_row(ui_conRecordListList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_conRecordListList, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imgRecordListVideo1 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo1, 240);
    lv_obj_set_height(ui_imgRecordListVideo1, 180);
    lv_obj_set_x(ui_imgRecordListVideo1, 337);
    lv_obj_set_y(ui_imgRecordListVideo1, 340);
    lv_obj_set_align(ui_imgRecordListVideo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo1,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo1, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo1, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_imgRecordListVideo2 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo2, 240);
    lv_obj_set_height(ui_imgRecordListVideo2, 180);
    lv_obj_set_x(ui_imgRecordListVideo2, 337);
    lv_obj_set_y(ui_imgRecordListVideo2, 340);
    lv_obj_set_align(ui_imgRecordListVideo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo2,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo2, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo2, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo2, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_imgRecordListVideo3 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo3, 240);
    lv_obj_set_height(ui_imgRecordListVideo3, 180);
    lv_obj_set_x(ui_imgRecordListVideo3, 337);
    lv_obj_set_y(ui_imgRecordListVideo3, 340);
    lv_obj_set_align(ui_imgRecordListVideo3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo3,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo3, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo3, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo3, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_imgRecordListVideo4 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo4, 240);
    lv_obj_set_height(ui_imgRecordListVideo4, 180);
    lv_obj_set_x(ui_imgRecordListVideo4, 337);
    lv_obj_set_y(ui_imgRecordListVideo4, 340);
    lv_obj_set_align(ui_imgRecordListVideo4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo4,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo4, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo4, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo4, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_imgRecordListVideo5 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo5, 240);
    lv_obj_set_height(ui_imgRecordListVideo5, 180);
    lv_obj_set_x(ui_imgRecordListVideo5, 337);
    lv_obj_set_y(ui_imgRecordListVideo5, 340);
    lv_obj_set_align(ui_imgRecordListVideo5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo5,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo5, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo5, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo5, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo5, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_imgRecordListVideo6 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo6, 240);
    lv_obj_set_height(ui_imgRecordListVideo6, 180);
    lv_obj_set_x(ui_imgRecordListVideo6, 337);
    lv_obj_set_y(ui_imgRecordListVideo6, 340);
    lv_obj_set_align(ui_imgRecordListVideo6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo6,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo6, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo6, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo6, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_imgRecordListVideo7 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo7, 240);
    lv_obj_set_height(ui_imgRecordListVideo7, 180);
    lv_obj_set_x(ui_imgRecordListVideo7, 337);
    lv_obj_set_y(ui_imgRecordListVideo7, 340);
    lv_obj_set_align(ui_imgRecordListVideo7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo7,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo7, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo7, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo7, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo7, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo7, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_imgRecordListVideo8 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo8, 240);
    lv_obj_set_height(ui_imgRecordListVideo8, 180);
    lv_obj_set_x(ui_imgRecordListVideo8, 337);
    lv_obj_set_y(ui_imgRecordListVideo8, 340);
    lv_obj_set_align(ui_imgRecordListVideo8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo8,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo8, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo8, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo8, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo8, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo8, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_imgRecordListVideo9 = lv_image_create(ui_conRecordListList);
    lv_obj_set_width(ui_imgRecordListVideo9, 240);
    lv_obj_set_height(ui_imgRecordListVideo9, 180);
    lv_obj_set_x(ui_imgRecordListVideo9, 337);
    lv_obj_set_y(ui_imgRecordListVideo9, 340);
    lv_obj_set_align(ui_imgRecordListVideo9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgRecordListVideo9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_imgRecordListVideo9,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_image_set_inner_align(ui_imgRecordListVideo9, LV_IMAGE_ALIGN_LEFT_MID);
    lv_obj_set_style_border_color(ui_imgRecordListVideo9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_imgRecordListVideo9, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_imgRecordListVideo9, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_imgRecordListVideo9, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_imgRecordListVideo9, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_btnRecordListPrePage = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_btnRecordListPrePage, 240);
    lv_obj_set_height(ui_btnRecordListPrePage, 80);
    lv_obj_set_x(ui_btnRecordListPrePage, -47);
    lv_obj_set_y(ui_btnRecordListPrePage, 92);
    lv_obj_set_align(ui_btnRecordListPrePage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRecordListPrePage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRecordListPrePage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRecordListPrePage,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRecordListPrePage, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRecordListPrePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRecordListPrePage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRecordListPrePage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRecordListPrePage, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRecordListPrePage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRecordListPrePage, &ui_img_arrow_back_80dp_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRecordListPrePage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRecordListPrePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRecordListPrePage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRecordListPlayPause = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_btnRecordListPlayPause, 80);
    lv_obj_set_height(ui_btnRecordListPlayPause, 80);
    lv_obj_set_x(ui_btnRecordListPlayPause, -47);
    lv_obj_set_y(ui_btnRecordListPlayPause, 92);
    lv_obj_set_align(ui_btnRecordListPlayPause, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRecordListPlayPause, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRecordListPlayPause, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRecordListPlayPause, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_btnRecordListPlayPause,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRecordListPlayPause, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRecordListPlayPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRecordListPlayPause, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRecordListPlayPause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRecordListPlayPause, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRecordListPlayPause, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRecordListPlayPause, &ui_img_play_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRecordListPlayPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRecordListPlayPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRecordListPlayPause, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnRecordListPlayPause, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnRecordListPlayPause, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_btnRecordListPlayPause, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_src(ui_btnRecordListPlayPause, &ui_img_pause_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_btnRecordListNextPage = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_btnRecordListNextPage, 240);
    lv_obj_set_height(ui_btnRecordListNextPage, 80);
    lv_obj_set_x(ui_btnRecordListNextPage, -47);
    lv_obj_set_y(ui_btnRecordListNextPage, 92);
    lv_obj_set_align(ui_btnRecordListNextPage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRecordListNextPage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRecordListNextPage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRecordListNextPage,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRecordListNextPage, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRecordListNextPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRecordListNextPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRecordListNextPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRecordListNextPage, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRecordListNextPage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRecordListNextPage, &ui_img_arrow_forward_80dp_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRecordListNextPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRecordListNextPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRecordListNextPage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRecordListPageInfo = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_lblRecordListPageInfo, 145);
    lv_obj_set_height(ui_lblRecordListPageInfo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblRecordListPageInfo, -68);
    lv_obj_set_y(ui_lblRecordListPageInfo, 190);
    lv_obj_set_align(ui_lblRecordListPageInfo, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRecordListPageInfo, "00/00");
    lv_obj_remove_flag(ui_lblRecordListPageInfo,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblRecordListPageInfo, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRecordListPageInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_lblRecordListPageInfo, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRecordListPageInfo, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Panel3);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 495);
    lv_obj_set_height(ui_Container6, 665);
    lv_obj_set_x(ui_Container6, -417);
    lv_obj_set_y(ui_Container6, -71);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container6, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label2, 190);
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -46);
    lv_obj_set_y(ui_Label2, 183);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Datetime");
    lv_obj_remove_flag(ui_Label2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInfoVideoDateTime = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblInfoVideoDateTime, 285);
    lv_obj_set_height(ui_lblInfoVideoDateTime, 70);
    lv_obj_set_x(ui_lblInfoVideoDateTime, 51);
    lv_obj_set_y(ui_lblInfoVideoDateTime, 200);
    lv_obj_set_align(ui_lblInfoVideoDateTime, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblInfoVideoDateTime, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblInfoVideoDateTime, "");
    lv_obj_remove_flag(ui_lblInfoVideoDateTime,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblInfoVideoDateTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfoVideoDateTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInfoVideoDateTime, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInfoVideoDateTime, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInfoVideoDateTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label13, 190);
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, -46);
    lv_obj_set_y(ui_Label13, 183);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Event");
    lv_obj_remove_flag(ui_Label13, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInfoVideoEvent = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblInfoVideoEvent, 285);
    lv_obj_set_height(ui_lblInfoVideoEvent, 75);
    lv_obj_set_x(ui_lblInfoVideoEvent, 51);
    lv_obj_set_y(ui_lblInfoVideoEvent, 200);
    lv_obj_set_align(ui_lblInfoVideoEvent, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblInfoVideoEvent, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblInfoVideoEvent, "");
    lv_obj_remove_flag(ui_lblInfoVideoEvent,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblInfoVideoEvent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfoVideoEvent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInfoVideoEvent, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInfoVideoEvent, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInfoVideoEvent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label7, 190);
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -46);
    lv_obj_set_y(ui_Label7, 183);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "Video name");
    lv_obj_remove_flag(ui_Label7, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInfoVideoName = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblInfoVideoName, 285);
    lv_obj_set_height(ui_lblInfoVideoName, 145);
    lv_obj_set_x(ui_lblInfoVideoName, 51);
    lv_obj_set_y(ui_lblInfoVideoName, 200);
    lv_obj_set_align(ui_lblInfoVideoName, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblInfoVideoName, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblInfoVideoName, "");
    lv_obj_remove_flag(ui_lblInfoVideoName,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblInfoVideoName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfoVideoName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInfoVideoName, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInfoVideoName, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInfoVideoName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label15, 190);
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, -46);
    lv_obj_set_y(ui_Label15, 183);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "Category");
    lv_obj_remove_flag(ui_Label15, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label15, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInfoVideoCategory = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblInfoVideoCategory, 285);
    lv_obj_set_height(ui_lblInfoVideoCategory, 40);
    lv_obj_set_x(ui_lblInfoVideoCategory, 51);
    lv_obj_set_y(ui_lblInfoVideoCategory, 200);
    lv_obj_set_align(ui_lblInfoVideoCategory, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblInfoVideoCategory, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblInfoVideoCategory, "");
    lv_obj_remove_flag(ui_lblInfoVideoCategory,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblInfoVideoCategory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfoVideoCategory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInfoVideoCategory, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInfoVideoCategory, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInfoVideoCategory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label21, 190);
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, -57);
    lv_obj_set_y(ui_Label21, 186);
    lv_obj_set_align(ui_Label21, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label21, "Description");
    lv_obj_remove_flag(ui_Label21, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInfoVideDesc = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblInfoVideDesc, 285);
    lv_obj_set_height(ui_lblInfoVideDesc, 145);
    lv_obj_set_x(ui_lblInfoVideDesc, 96);
    lv_obj_set_y(ui_lblInfoVideDesc, 185);
    lv_obj_set_align(ui_lblInfoVideDesc, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblInfoVideDesc, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblInfoVideDesc, "");
    lv_obj_remove_flag(ui_lblInfoVideDesc,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblInfoVideDesc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfoVideDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInfoVideDesc, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInfoVideDesc, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInfoVideDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_Label22, 190);
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, -46);
    lv_obj_set_y(ui_Label22, 183);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "Author");
    lv_obj_remove_flag(ui_Label22, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblInfoVideoAuthor = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_lblInfoVideoAuthor, 285);
    lv_obj_set_height(ui_lblInfoVideoAuthor, 40);
    lv_obj_set_x(ui_lblInfoVideoAuthor, 23);
    lv_obj_set_y(ui_lblInfoVideoAuthor, 200);
    lv_obj_set_align(ui_lblInfoVideoAuthor, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblInfoVideoAuthor, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblInfoVideoAuthor, "");
    lv_obj_remove_flag(ui_lblInfoVideoAuthor,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblInfoVideoAuthor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblInfoVideoAuthor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblInfoVideoAuthor, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblInfoVideoAuthor, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblInfoVideoAuthor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRecordListDelete = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_btnRecordListDelete, 80);
    lv_obj_set_height(ui_btnRecordListDelete, 80);
    lv_obj_set_x(ui_btnRecordListDelete, -47);
    lv_obj_set_y(ui_btnRecordListDelete, 92);
    lv_obj_set_align(ui_btnRecordListDelete, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRecordListDelete, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRecordListDelete, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRecordListDelete,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRecordListDelete, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRecordListDelete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRecordListDelete, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRecordListDelete, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRecordListDelete, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRecordListDelete, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRecordListDelete, &ui_img_delete_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRecordListDelete, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRecordListDelete, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRecordListDelete, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRecordListTransfer = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_btnRecordListTransfer, 80);
    lv_obj_set_height(ui_btnRecordListTransfer, 80);
    lv_obj_set_x(ui_btnRecordListTransfer, -47);
    lv_obj_set_y(ui_btnRecordListTransfer, 92);
    lv_obj_set_align(ui_btnRecordListTransfer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRecordListTransfer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRecordListTransfer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRecordListTransfer,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRecordListTransfer, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRecordListTransfer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRecordListTransfer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRecordListTransfer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRecordListTransfer, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRecordListTransfer, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRecordListTransfer, &ui_img_drive_file_move_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRecordListTransfer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRecordListTransfer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRecordListTransfer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropPortableMemory = lv_dropdown_create(ui_Container6);
    lv_dropdown_set_selected_highlight(ui_dropPortableMemory, false);
    lv_obj_set_width(ui_dropPortableMemory, 200);
    lv_obj_set_height(ui_dropPortableMemory, 80);
    lv_obj_set_x(ui_dropPortableMemory, -194);
    lv_obj_set_y(ui_dropPortableMemory, -313);
    lv_obj_set_align(ui_dropPortableMemory, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dropPortableMemory,
                       LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_dropPortableMemory, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_dropPortableMemory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dropPortableMemory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dropPortableMemory, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dropPortableMemory, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dropPortableMemory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dropPortableMemory, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_dropPortableMemory), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_dropPortableMemory), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_dropPortableMemory), &lv_font_montserrat_46,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_dropPortableMemory), lv_color_hex(0x424242),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_dropPortableMemory), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRecordListBack = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_btnRecordListBack, 100);
    lv_obj_set_height(ui_btnRecordListBack, 80);
    lv_obj_set_x(ui_btnRecordListBack, -47);
    lv_obj_set_y(ui_btnRecordListBack, 92);
    lv_obj_set_align(ui_btnRecordListBack, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRecordListBack, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRecordListBack, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRecordListBack,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRecordListBack, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRecordListBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRecordListBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRecordListBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRecordListBack, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRecordListBack, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRecordListBack, &ui_img_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRecordListBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRecordListBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRecordListBack, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnVideoSearch, ui_event_btnVideoSearch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dropVideoFilter, ui_event_dropVideoFilter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo1, ui_event_imgRecordListVideo1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo2, ui_event_imgRecordListVideo2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo3, ui_event_imgRecordListVideo3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo4, ui_event_imgRecordListVideo4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo5, ui_event_imgRecordListVideo5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo6, ui_event_imgRecordListVideo6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo7, ui_event_imgRecordListVideo7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo8, ui_event_imgRecordListVideo8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_imgRecordListVideo9, ui_event_imgRecordListVideo9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRecordListPrePage, ui_event_btnRecordListPrePage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRecordListPlayPause, ui_event_btnRecordListPlayPause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRecordListNextPage, ui_event_btnRecordListNextPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRecordListDelete, ui_event_btnRecordListDelete, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRecordListTransfer, ui_event_btnRecordListTransfer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dropPortableMemory, ui_event_dropPortableMemory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRecordListBack, ui_event_btnRecordListBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RecordList, ui_event_RecordList, LV_EVENT_ALL, NULL);

}

void ui_RecordList_screen_destroy(void)
{
    if(ui_RecordList) lv_obj_del(ui_RecordList);

    // NULL screen variables
    ui_RecordList = NULL;
    ui_lblVideoSearch = NULL;
    ui_btnVideoSearch = NULL;
    ui_dropVideoFilter = NULL;
    ui_Image2 = NULL;
    ui_Panel3 = NULL;
    ui_Container5 = NULL;
    ui_conRecordListList = NULL;
    ui_imgRecordListVideo1 = NULL;
    ui_imgRecordListVideo2 = NULL;
    ui_imgRecordListVideo3 = NULL;
    ui_imgRecordListVideo4 = NULL;
    ui_imgRecordListVideo5 = NULL;
    ui_imgRecordListVideo6 = NULL;
    ui_imgRecordListVideo7 = NULL;
    ui_imgRecordListVideo8 = NULL;
    ui_imgRecordListVideo9 = NULL;
    ui_btnRecordListPrePage = NULL;
    ui_btnRecordListPlayPause = NULL;
    ui_btnRecordListNextPage = NULL;
    ui_lblRecordListPageInfo = NULL;
    ui_Container6 = NULL;
    ui_Label2 = NULL;
    ui_lblInfoVideoDateTime = NULL;
    ui_Label13 = NULL;
    ui_lblInfoVideoEvent = NULL;
    ui_Label7 = NULL;
    ui_lblInfoVideoName = NULL;
    ui_Label15 = NULL;
    ui_lblInfoVideoCategory = NULL;
    ui_Label21 = NULL;
    ui_lblInfoVideDesc = NULL;
    ui_Label22 = NULL;
    ui_lblInfoVideoAuthor = NULL;
    ui_btnRecordListDelete = NULL;
    ui_btnRecordListTransfer = NULL;
    ui_dropPortableMemory = NULL;
    ui_btnRecordListBack = NULL;

}
