// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#include "../ui.h"

lv_obj_t * ui_RecordList = NULL;
lv_obj_t * ui_lblVideoSearch = NULL;
lv_obj_t * ui_btnVideoSearch = NULL;
lv_obj_t * ui_dropVideoFilter = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_cbRLItemAll = NULL;
lv_obj_t * ui_conRL = NULL;
lv_obj_t * ui_conRLItemRow1 = NULL;
lv_obj_t * ui_cbRLItem1 = NULL;
lv_obj_t * ui_cbRLItemTransfer1 = NULL;
lv_obj_t * ui_lblRLItemDateTime1 = NULL;
lv_obj_t * ui_lblRLItemName1 = NULL;
lv_obj_t * ui_Con2 = NULL;
lv_obj_t * ui_btnRLTopPage = NULL;
lv_obj_t * ui_btnRLPrePage = NULL;
lv_obj_t * ui_btnRLNextPage = NULL;
lv_obj_t * ui_btnRLBottomPage = NULL;
lv_obj_t * ui_btnRLPlay = NULL;
lv_obj_t * ui_btnRLPause = NULL;
lv_obj_t * ui_btnRLStop = NULL;
lv_obj_t * ui_btnRLFastRewind = NULL;
lv_obj_t * ui_btnRLFastForward = NULL;
lv_obj_t * ui_btnRLSound = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_btnRLNewRecord = NULL;
lv_obj_t * ui_barDeleteWaiting = NULL;
lv_obj_t * ui_dropPortableMemory = NULL;
lv_obj_t * ui_barTransferProgress = NULL;
lv_obj_t * ui_btnRLTransfer = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_btnRLDukto = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_btnRLBack = NULL;
lv_obj_t * ui_wndRLBlock = NULL;
// event funtions
void ui_event_RecordList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        CommonOnLoaded(e);
    }
}

void ui_event_btnVideoSearch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_dropVideoFilter(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CommonDropdownOnValueChange(e);
    }
}

void ui_event_cbRLItemAll(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_conRLItemRow1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLTopPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLPrePage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        CommonButtonOnClick(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        CommonButtonOnLongPressRepeat(e);
    }
}

void ui_event_btnRLNextPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        CommonButtonOnClick(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        CommonButtonOnLongPressRepeat(e);
    }
}

void ui_event_btnRLBottomPage(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLPlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLPause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLStop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLFastRewind(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLFastForward(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLSound(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLNewRecord(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_barDeleteWaiting(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        CommonButtonOnLongPressRepeat(e);
    }
    if(event_code == LV_EVENT_RELEASED) {
        CommonButtonOnRelease(e);
    }
}

void ui_event_dropPortableMemory(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        CommonButtonOnValueChange(e);
    }
}

void ui_event_btnRLTransfer(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLDukto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnRLBack(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

// build funtions

void ui_RecordList_screen_init(void)
{
    ui_RecordList = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RecordList, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);    /// Flags
    lv_obj_set_flex_flow(ui_RecordList, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_RecordList, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_RecordList, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RecordList, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVideoSearch = lv_label_create(ui_RecordList);
    lv_obj_set_width(ui_lblVideoSearch, 680);
    lv_obj_set_height(ui_lblVideoSearch, 80);
    lv_obj_set_x(ui_lblVideoSearch, 107);
    lv_obj_set_y(ui_lblVideoSearch, 177);
    lv_obj_set_align(ui_lblVideoSearch, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblVideoSearch, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblVideoSearch, "");
    lv_obj_remove_flag(ui_lblVideoSearch,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblVideoSearch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblVideoSearch, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblVideoSearch, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_lblVideoSearch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_lblVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lblVideoSearch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnVideoSearch = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnVideoSearch, 80);
    lv_obj_set_height(ui_btnVideoSearch, 80);
    lv_obj_set_x(ui_btnVideoSearch, -47);
    lv_obj_set_y(ui_btnVideoSearch, 92);
    lv_obj_set_align(ui_btnVideoSearch, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnVideoSearch, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnVideoSearch, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnVideoSearch,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnVideoSearch, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnVideoSearch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnVideoSearch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnVideoSearch, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnVideoSearch, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnVideoSearch, &ui_img_search_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnVideoSearch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnVideoSearch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnVideoSearch, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_dropVideoFilter = lv_dropdown_create(ui_RecordList);
    lv_dropdown_set_selected_highlight(ui_dropVideoFilter, false);
    lv_obj_set_width(ui_dropVideoFilter, 360);
    lv_obj_set_height(ui_dropVideoFilter, 80);
    lv_obj_set_x(ui_dropVideoFilter, -194);
    lv_obj_set_y(ui_dropVideoFilter, -313);
    lv_obj_set_align(ui_dropVideoFilter, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dropVideoFilter,
                       LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_dropVideoFilter, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_dropVideoFilter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dropVideoFilter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dropVideoFilter, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dropVideoFilter, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dropVideoFilter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dropVideoFilter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dropVideoFilter, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dropVideoFilter, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_dropVideoFilter), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_dropVideoFilter), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_dropVideoFilter), &lv_font_montserrat_46,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_dropVideoFilter), lv_color_hex(0x424242),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_dropVideoFilter), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_RecordList);
    lv_image_set_src(ui_Image2, &ui_img_filter_png);
    lv_obj_set_width(ui_Image2, 55);
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, 599);
    lv_obj_set_y(ui_Image2, -234);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cbRLItemAll = lv_checkbox_create(ui_RecordList);
    lv_obj_set_width(ui_cbRLItemAll, 60);
    lv_obj_set_height(ui_cbRLItemAll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cbRLItemAll, -106);
    lv_obj_set_y(ui_cbRLItemAll, -98);
    lv_obj_set_align(ui_cbRLItemAll, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbRLItemAll, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_cbRLItemAll, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_image_src(ui_cbRLItemAll, &ui_img_check_png, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_conRL = lv_obj_create(ui_RecordList);
    lv_obj_remove_style_all(ui_conRL);
    lv_obj_set_width(ui_conRL, 1175);
    lv_obj_set_height(ui_conRL, 570);
    lv_obj_set_x(ui_conRL, -419);
    lv_obj_set_y(ui_conRL, -51);
    lv_obj_set_align(ui_conRL, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conRL, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_conRL, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_conRL, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_conRL, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_conRL, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_conRL, LV_SCROLL_SNAP_END);
    lv_obj_set_scroll_snap_y(ui_conRL, LV_SCROLL_SNAP_END);
    lv_obj_set_style_pad_row(ui_conRL, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_conRL, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_conRLItemRow1 = lv_obj_create(ui_conRL);
    lv_obj_remove_style_all(ui_conRLItemRow1);
    lv_obj_set_height(ui_conRLItemRow1, 110);
    lv_obj_set_width(ui_conRLItemRow1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_conRLItemRow1, -419);
    lv_obj_set_y(ui_conRLItemRow1, -51);
    lv_obj_set_align(ui_conRLItemRow1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_conRLItemRow1, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_conRLItemRow1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_conRLItemRow1, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_conRLItemRow1,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_border_color(ui_conRLItemRow1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_conRLItemRow1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_conRLItemRow1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_conRLItemRow1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_conRLItemRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_conRLItemRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_conRLItemRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_conRLItemRow1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_conRLItemRow1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_conRLItemRow1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(ui_conRLItemRow1, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_conRLItemRow1, 5, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_cbRLItem1 = lv_checkbox_create(ui_conRLItemRow1);
    lv_obj_set_width(ui_cbRLItem1, 50);
    lv_obj_set_height(ui_cbRLItem1, 45);
    lv_obj_set_x(ui_cbRLItem1, -106);
    lv_obj_set_y(ui_cbRLItem1, -98);
    lv_obj_set_align(ui_cbRLItem1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbRLItem1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_cbRLItem1, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_image_src(ui_cbRLItem1, &ui_img_check_png, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_cbRLItemTransfer1 = lv_checkbox_create(ui_conRLItemRow1);
    lv_obj_set_width(ui_cbRLItemTransfer1, 50);
    lv_obj_set_height(ui_cbRLItemTransfer1, 45);
    lv_obj_set_x(ui_cbRLItemTransfer1, -106);
    lv_obj_set_y(ui_cbRLItemTransfer1, -99);
    lv_obj_set_align(ui_cbRLItemTransfer1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_cbRLItemTransfer1,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_font(ui_cbRLItemTransfer1, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_cbRLItemTransfer1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cbRLItemTransfer1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_cbRLItemTransfer1, &ui_img_folder_check_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cbRLItemTransfer1, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cbRLItemTransfer1, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_cbRLItemTransfer1, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_src(ui_cbRLItemTransfer1, &ui_img_folder_limited_png, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_recolor(ui_cbRLItemTransfer1, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_recolor_opa(ui_cbRLItemTransfer1, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(ui_cbRLItemTransfer1, 0, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_lblRLItemDateTime1 = lv_label_create(ui_conRLItemRow1);
    lv_obj_set_width(ui_lblRLItemDateTime1, 265);
    lv_obj_set_height(ui_lblRLItemDateTime1, 100);
    lv_obj_set_x(ui_lblRLItemDateTime1, 75);
    lv_obj_set_y(ui_lblRLItemDateTime1, 184);
    lv_obj_set_align(ui_lblRLItemDateTime1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblRLItemDateTime1, "");
    lv_obj_remove_flag(ui_lblRLItemDateTime1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblRLItemDateTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRLItemDateTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRLItemDateTime1, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblRLItemDateTime1, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblRLItemDateTime1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblRLItemName1 = lv_label_create(ui_conRLItemRow1);
    lv_obj_set_width(ui_lblRLItemName1, 840);
    lv_obj_set_height(ui_lblRLItemName1, 100);
    lv_obj_set_x(ui_lblRLItemName1, 38);
    lv_obj_set_y(ui_lblRLItemName1, 189);
    lv_obj_set_align(ui_lblRLItemName1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_lblRLItemName1, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_lblRLItemName1, "");
    lv_obj_remove_flag(ui_lblRLItemName1,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblRLItemName1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblRLItemName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblRLItemName1, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblRLItemName1, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblRLItemName1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Con2 = lv_obj_create(ui_RecordList);
    lv_obj_remove_style_all(ui_Con2);
    lv_obj_set_width(ui_Con2, 90);
    lv_obj_set_height(ui_Con2, 570);
    lv_obj_set_x(ui_Con2, -419);
    lv_obj_set_y(ui_Con2, -53);
    lv_obj_set_align(ui_Con2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Con2, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Con2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Con2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_Con2, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Con2, LV_DIR_VER);
    lv_obj_set_scroll_snap_x(ui_Con2, LV_SCROLL_SNAP_END);
    lv_obj_set_scroll_snap_y(ui_Con2, LV_SCROLL_SNAP_END);
    lv_obj_set_style_pad_row(ui_Con2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Con2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLTopPage = lv_button_create(ui_Con2);
    lv_obj_set_width(ui_btnRLTopPage, 80);
    lv_obj_set_height(ui_btnRLTopPage, 80);
    lv_obj_set_x(ui_btnRLTopPage, -47);
    lv_obj_set_y(ui_btnRLTopPage, 92);
    lv_obj_set_align(ui_btnRLTopPage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLTopPage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLTopPage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLTopPage, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLTopPage, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLTopPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLTopPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLTopPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLTopPage, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLTopPage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLTopPage, &ui_img_vertical_align_top_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLTopPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLTopPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLTopPage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLPrePage = lv_button_create(ui_Con2);
    lv_obj_set_width(ui_btnRLPrePage, 80);
    lv_obj_set_height(ui_btnRLPrePage, 190);
    lv_obj_set_x(ui_btnRLPrePage, -47);
    lv_obj_set_y(ui_btnRLPrePage, 92);
    lv_obj_set_align(ui_btnRLPrePage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLPrePage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLPrePage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLPrePage, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLPrePage, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLPrePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLPrePage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLPrePage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLPrePage, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLPrePage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLPrePage, &ui_img_arrow_upward_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLPrePage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLPrePage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLPrePage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLNextPage = lv_button_create(ui_Con2);
    lv_obj_set_width(ui_btnRLNextPage, 80);
    lv_obj_set_height(ui_btnRLNextPage, 190);
    lv_obj_set_x(ui_btnRLNextPage, -47);
    lv_obj_set_y(ui_btnRLNextPage, 92);
    lv_obj_set_align(ui_btnRLNextPage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLNextPage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLNextPage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLNextPage,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLNextPage, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLNextPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLNextPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLNextPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLNextPage, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLNextPage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLNextPage, &ui_img_arrow_downward_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLNextPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLNextPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLNextPage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLBottomPage = lv_button_create(ui_Con2);
    lv_obj_set_width(ui_btnRLBottomPage, 80);
    lv_obj_set_height(ui_btnRLBottomPage, 80);
    lv_obj_set_x(ui_btnRLBottomPage, -47);
    lv_obj_set_y(ui_btnRLBottomPage, 92);
    lv_obj_set_align(ui_btnRLBottomPage, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLBottomPage, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLBottomPage, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLBottomPage,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLBottomPage, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLBottomPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLBottomPage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLBottomPage, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLBottomPage, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLBottomPage, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLBottomPage, &ui_img_vertical_align_bottom_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLBottomPage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLBottomPage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLBottomPage, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLPlay = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLPlay, 80);
    lv_obj_set_height(ui_btnRLPlay, 80);
    lv_obj_set_x(ui_btnRLPlay, -47);
    lv_obj_set_y(ui_btnRLPlay, 92);
    lv_obj_set_align(ui_btnRLPlay, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLPlay, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLPlay, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLPlay, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLPlay, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLPlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLPlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLPlay, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLPlay, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLPlay, &ui_img_play_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLPlay, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLPlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLPlay, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLPause = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLPause, 80);
    lv_obj_set_height(ui_btnRLPause, 80);
    lv_obj_set_x(ui_btnRLPause, -47);
    lv_obj_set_y(ui_btnRLPause, 92);
    lv_obj_set_align(ui_btnRLPause, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLPause, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLPause, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLPause, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLPause, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLPause, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLPause, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLPause, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLPause, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLPause, &ui_img_pause_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLPause, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLPause, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLPause, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLStop = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLStop, 80);
    lv_obj_set_height(ui_btnRLStop, 80);
    lv_obj_set_x(ui_btnRLStop, -47);
    lv_obj_set_y(ui_btnRLStop, 92);
    lv_obj_set_align(ui_btnRLStop, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLStop, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLStop, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLStop, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLStop, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLStop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLStop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLStop, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLStop, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLStop, &ui_img_stop_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLStop, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLStop, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLFastRewind = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLFastRewind, 80);
    lv_obj_set_height(ui_btnRLFastRewind, 80);
    lv_obj_set_x(ui_btnRLFastRewind, -47);
    lv_obj_set_y(ui_btnRLFastRewind, 92);
    lv_obj_set_align(ui_btnRLFastRewind, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLFastRewind, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLFastRewind, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLFastRewind,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLFastRewind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLFastRewind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLFastRewind, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLFastRewind, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLFastRewind, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLFastRewind, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLFastRewind, &ui_img_fast_rewind_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLFastRewind, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLFastRewind, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLFastRewind, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLFastForward = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLFastForward, 80);
    lv_obj_set_height(ui_btnRLFastForward, 80);
    lv_obj_set_x(ui_btnRLFastForward, -47);
    lv_obj_set_y(ui_btnRLFastForward, 92);
    lv_obj_set_align(ui_btnRLFastForward, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLFastForward, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLFastForward, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLFastForward,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLFastForward, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLFastForward, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLFastForward, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLFastForward, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLFastForward, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLFastForward, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLFastForward, &ui_img_fast_forward_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLFastForward, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLFastForward, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLFastForward, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLSound = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLSound, 80);
    lv_obj_set_height(ui_btnRLSound, 80);
    lv_obj_set_x(ui_btnRLSound, -47);
    lv_obj_set_y(ui_btnRLSound, 92);
    lv_obj_set_align(ui_btnRLSound, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLSound, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLSound, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnRLSound, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_btnRLSound, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLSound, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLSound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLSound, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLSound, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLSound, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLSound, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLSound, &ui_img_brand_awareness_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLSound, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLSound, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLSound, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_btnRLSound, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_btnRLSound, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_grad_color(ui_btnRLSound, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_image_src(ui_btnRLSound, &ui_img_no_sound_png, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Label2 = lv_label_create(ui_RecordList);
    lv_obj_set_width(ui_Label2, 5);
    lv_obj_set_height(ui_Label2, 80);
    lv_obj_set_x(ui_Label2, -273);
    lv_obj_set_y(ui_Label2, 208);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "");
    lv_obj_set_style_bg_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLNewRecord = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLNewRecord, 80);
    lv_obj_set_height(ui_btnRLNewRecord, 80);
    lv_obj_set_x(ui_btnRLNewRecord, -47);
    lv_obj_set_y(ui_btnRLNewRecord, 92);
    lv_obj_set_align(ui_btnRLNewRecord, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLNewRecord, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLNewRecord, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLNewRecord,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLNewRecord, lv_color_hex(0x00BD00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLNewRecord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLNewRecord, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLNewRecord, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLNewRecord, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLNewRecord, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLNewRecord, &ui_img_replace_video_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLNewRecord, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLNewRecord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLNewRecord, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barDeleteWaiting = lv_bar_create(ui_RecordList);
    lv_bar_set_range(ui_barDeleteWaiting, 0, 300);
    lv_obj_set_width(ui_barDeleteWaiting, 80);
    lv_obj_set_height(ui_barDeleteWaiting, 80);
    lv_obj_set_x(ui_barDeleteWaiting, 101);
    lv_obj_set_y(ui_barDeleteWaiting, 314);
    lv_obj_set_align(ui_barDeleteWaiting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barDeleteWaiting, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_barDeleteWaiting,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_barDeleteWaiting, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barDeleteWaiting, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barDeleteWaiting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_barDeleteWaiting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_barDeleteWaiting, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_barDeleteWaiting, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_barDeleteWaiting, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_barDeleteWaiting, &ui_img_delete_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_barDeleteWaiting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_barDeleteWaiting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_barDeleteWaiting, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barDeleteWaiting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_opa(ui_barDeleteWaiting, 100, LV_PART_MAIN | LV_STATE_DISABLED);
    lv_obj_set_style_bg_grad_color(ui_barDeleteWaiting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DISABLED);

    lv_obj_set_style_radius(ui_barDeleteWaiting, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barDeleteWaiting, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barDeleteWaiting, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_barDeleteWaiting, &ui_img_delete_png, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barDeleteWaiting, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barDeleteWaiting,
                                                                                                       lv_obj_get_style_pad_right(ui_barDeleteWaiting, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_dropPortableMemory = lv_dropdown_create(ui_RecordList);
    lv_dropdown_set_selected_highlight(ui_dropPortableMemory, false);
    lv_obj_set_width(ui_dropPortableMemory, 215);
    lv_obj_set_height(ui_dropPortableMemory, 80);
    lv_obj_set_x(ui_dropPortableMemory, -194);
    lv_obj_set_y(ui_dropPortableMemory, -313);
    lv_obj_set_align(ui_dropPortableMemory, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_dropPortableMemory, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_dropPortableMemory, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_dropPortableMemory,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_scrollbar_mode(ui_dropPortableMemory, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_style_text_color(ui_dropPortableMemory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_dropPortableMemory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_dropPortableMemory, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_dropPortableMemory, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_dropPortableMemory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_dropPortableMemory, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_dropPortableMemory, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_dropPortableMemory, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_dropPortableMemory), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_dropPortableMemory), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_dropPortableMemory), &lv_font_montserrat_46,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_dropPortableMemory), lv_color_hex(0x424242),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_dropPortableMemory), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_barTransferProgress = lv_bar_create(ui_dropPortableMemory);
    lv_obj_set_width(ui_barTransferProgress, 215);
    lv_obj_set_height(ui_barTransferProgress, 80);
    lv_obj_set_x(ui_barTransferProgress, 96);
    lv_obj_set_y(ui_barTransferProgress, 314);
    lv_obj_set_align(ui_barTransferProgress, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_barTransferProgress, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_barTransferProgress,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_radius(ui_barTransferProgress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barTransferProgress, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barTransferProgress, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_barTransferProgress, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_barTransferProgress, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_barTransferProgress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_barTransferProgress,
                                LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_barTransferProgress, lv_obj_get_style_pad_right(ui_barTransferProgress,
                                                                                  LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_btnRLTransfer = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLTransfer, 80);
    lv_obj_set_height(ui_btnRLTransfer, 80);
    lv_obj_set_x(ui_btnRLTransfer, -47);
    lv_obj_set_y(ui_btnRLTransfer, 92);
    lv_obj_set_align(ui_btnRLTransfer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLTransfer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLTransfer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLTransfer,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLTransfer, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLTransfer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLTransfer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLTransfer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLTransfer, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLTransfer, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLTransfer, &ui_img_drive_file_move_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLTransfer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLTransfer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLTransfer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_RecordList);
    lv_obj_set_width(ui_Label1, 5);
    lv_obj_set_height(ui_Label1, 80);
    lv_obj_set_x(ui_Label1, -273);
    lv_obj_set_y(ui_Label1, 208);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "");
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLDukto = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLDukto, 80);
    lv_obj_set_height(ui_btnRLDukto, 80);
    lv_obj_set_x(ui_btnRLDukto, -47);
    lv_obj_set_y(ui_btnRLDukto, 92);
    lv_obj_set_align(ui_btnRLDukto, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLDukto, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLDukto, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLDukto, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLDukto, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLDukto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLDukto, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLDukto, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLDukto, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLDukto, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLDukto, &ui_img_dukto_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLDukto, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLDukto, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLDukto, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_RecordList);
    lv_obj_set_width(ui_Label3, 5);
    lv_obj_set_height(ui_Label3, 80);
    lv_obj_set_x(ui_Label3, -273);
    lv_obj_set_y(ui_Label3, 208);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "");
    lv_obj_set_style_bg_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnRLBack = lv_button_create(ui_RecordList);
    lv_obj_set_width(ui_btnRLBack, 95);
    lv_obj_set_height(ui_btnRLBack, 80);
    lv_obj_set_x(ui_btnRLBack, -54);
    lv_obj_set_y(ui_btnRLBack, 94);
    lv_obj_set_align(ui_btnRLBack, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnRLBack, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnRLBack, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnRLBack, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnRLBack, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnRLBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnRLBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnRLBack, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnRLBack, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnRLBack, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnRLBack, &ui_img_cancel_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnRLBack, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnRLBack, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnRLBack, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wndRLBlock = lv_obj_create(ui_RecordList);
    lv_obj_remove_style_all(ui_wndRLBlock);
    lv_obj_set_width(ui_wndRLBlock, 1280);
    lv_obj_set_height(ui_wndRLBlock, 768);
    lv_obj_set_align(ui_wndRLBlock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wndRLBlock, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_FLOATING);     /// Flags
    lv_obj_remove_flag(ui_wndRLBlock, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_wndRLBlock, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wndRLBlock, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnVideoSearch, ui_event_btnVideoSearch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dropVideoFilter, ui_event_dropVideoFilter, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_cbRLItemAll, ui_event_cbRLItemAll, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_conRLItemRow1, ui_event_conRLItemRow1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLTopPage, ui_event_btnRLTopPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLPrePage, ui_event_btnRLPrePage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLNextPage, ui_event_btnRLNextPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLBottomPage, ui_event_btnRLBottomPage, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLPlay, ui_event_btnRLPlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLPause, ui_event_btnRLPause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLStop, ui_event_btnRLStop, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLFastRewind, ui_event_btnRLFastRewind, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLFastForward, ui_event_btnRLFastForward, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLSound, ui_event_btnRLSound, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLNewRecord, ui_event_btnRLNewRecord, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_barDeleteWaiting, ui_event_barDeleteWaiting, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_dropPortableMemory, ui_event_dropPortableMemory, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLTransfer, ui_event_btnRLTransfer, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLDukto, ui_event_btnRLDukto, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnRLBack, ui_event_btnRLBack, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RecordList, ui_event_RecordList, LV_EVENT_ALL, NULL);

}

void ui_RecordList_screen_destroy(void)
{
    if(ui_RecordList) lv_obj_del(ui_RecordList);

    // NULL screen variables
    ui_RecordList = NULL;
    ui_lblVideoSearch = NULL;
    ui_btnVideoSearch = NULL;
    ui_dropVideoFilter = NULL;
    ui_Image2 = NULL;
    ui_cbRLItemAll = NULL;
    ui_conRL = NULL;
    ui_conRLItemRow1 = NULL;
    ui_cbRLItem1 = NULL;
    ui_cbRLItemTransfer1 = NULL;
    ui_lblRLItemDateTime1 = NULL;
    ui_lblRLItemName1 = NULL;
    ui_Con2 = NULL;
    ui_btnRLTopPage = NULL;
    ui_btnRLPrePage = NULL;
    ui_btnRLNextPage = NULL;
    ui_btnRLBottomPage = NULL;
    ui_btnRLPlay = NULL;
    ui_btnRLPause = NULL;
    ui_btnRLStop = NULL;
    ui_btnRLFastRewind = NULL;
    ui_btnRLFastForward = NULL;
    ui_btnRLSound = NULL;
    ui_Label2 = NULL;
    ui_btnRLNewRecord = NULL;
    ui_barDeleteWaiting = NULL;
    ui_dropPortableMemory = NULL;
    ui_barTransferProgress = NULL;
    ui_btnRLTransfer = NULL;
    ui_Label1 = NULL;
    ui_btnRLDukto = NULL;
    ui_Label3 = NULL;
    ui_btnRLBack = NULL;
    ui_wndRLBlock = NULL;

}
