// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#ifndef UI_SETTING_H
#define UI_SETTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Setting
extern void ui_Setting_screen_init(void);
extern void ui_Setting_screen_destroy(void);
extern lv_obj_t * ui_Setting;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_tabSettingList;
extern lv_obj_t * ui_tabGeneral;
extern lv_obj_t * ui_Label5;
extern void ui_event_dropDateFormat(lv_event_t * e);
extern lv_obj_t * ui_dropDateFormat;
extern lv_obj_t * ui_Label6;
extern void ui_event_dropDateSeparator(lv_event_t * e);
extern lv_obj_t * ui_dropDateSeparator;
extern lv_obj_t * ui_Label7;
extern void ui_event_swInitAudState(lv_event_t * e);
extern lv_obj_t * ui_swInitAudState;
extern lv_obj_t * ui_Label8;
extern void ui_event_swPreviewVideo(lv_event_t * e);
extern lv_obj_t * ui_swPreviewVideo;
extern lv_obj_t * ui_Label9;
extern void ui_event_swPlayVideo(lv_event_t * e);
extern lv_obj_t * ui_swPlayVideo;
extern lv_obj_t * ui_tabKeyboard;
extern lv_obj_t * ui_Label10;
extern void ui_event_dropKeyboardType(lv_event_t * e);
extern lv_obj_t * ui_dropKeyboardType;
extern lv_obj_t * ui_lblT9AutoConfirm;
extern void ui_event_dropT9AutoConfirm(lv_event_t * e);
extern lv_obj_t * ui_dropT9AutoConfirm;
extern lv_obj_t * ui_Label12;
extern void ui_event_swKeyboardExitShortcut(lv_event_t * e);
extern lv_obj_t * ui_swKeyboardExitShortcut;
extern lv_obj_t * ui_Label13;
extern void ui_event_swInsSpaceAfterPunc(lv_event_t * e);
extern lv_obj_t * ui_swInsSpaceAfterPunc;
extern lv_obj_t * ui_Label14;
extern void ui_event_swAutoCloseBracket(lv_event_t * e);
extern lv_obj_t * ui_swAutoCloseBracket;
extern lv_obj_t * ui_tabNetwork;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_lblConnectState;
extern void ui_event_dropNetworkType(lv_event_t * e);
extern lv_obj_t * ui_dropNetworkType;
extern lv_obj_t * ui_lblSSID;
extern void ui_event_dropSSID(lv_event_t * e);
extern lv_obj_t * ui_dropSSID;
extern lv_obj_t * ui_lblTitleWiFiPass;
extern lv_obj_t * ui_lblWifiPass;
extern void ui_event_btnWifiPass(lv_event_t * e);
extern lv_obj_t * ui_btnWifiPass;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_lblIpv4Addr;
extern void ui_event_btnIpv4Addr(lv_event_t * e);
extern lv_obj_t * ui_btnIpv4Addr;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_lblSubnetAddr;
extern void ui_event_btnSubnetAddr(lv_event_t * e);
extern lv_obj_t * ui_btnSubnetAddr;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_lblDefaultGateway;
extern void ui_event_btnDefaultGateway(lv_event_t * e);
extern lv_obj_t * ui_btnDefaultGateway;
extern lv_obj_t * ui_Container6;
extern void ui_event_btnSettingCancel(lv_event_t * e);
extern lv_obj_t * ui_btnSettingCancel;
extern void ui_event_btnSettingSave(lv_event_t * e);
extern lv_obj_t * ui_btnSettingSave;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

