// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#ifndef UI_VIDEOINPUT_H
#define UI_VIDEOINPUT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_VideoInput
extern void ui_VideoInput_screen_init(void);
extern void ui_VideoInput_screen_destroy(void);
extern void ui_event_VideoInput(lv_event_t * e);
extern lv_obj_t * ui_VideoInput;
extern lv_obj_t * ui_lblVideoInputTitle;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_lblVideoId;
extern void ui_event_btnVideoId(lv_event_t * e);
extern lv_obj_t * ui_btnVideoId;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_lblVideoName;
extern void ui_event_btnVideoName(lv_event_t * e);
extern lv_obj_t * ui_btnVideoName;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_cbVideoInputTags;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_lblVideoInputDesc;
extern void ui_event_btnVideoInputDesc(lv_event_t * e);
extern lv_obj_t * ui_btnVideoInputDesc;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_cbVideoInputAuthor;
extern lv_obj_t * ui_Container2;
extern void ui_event_btnVideoInputCancel(lv_event_t * e);
extern lv_obj_t * ui_btnVideoInputCancel;
extern lv_obj_t * ui_Label26;
extern void ui_event_btnVideoInputOK(lv_event_t * e);
extern lv_obj_t * ui_btnVideoInputOK;
extern lv_obj_t * ui_Label14;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

