// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.1.0
// Project name: DVR-TT01

#include "../ui.h"

lv_obj_t * ui_VideoInput = NULL;
lv_obj_t * ui_lblVideoInputTitle = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_lblVideoId = NULL;
lv_obj_t * ui_btnVideoId = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_lblVideoName = NULL;
lv_obj_t * ui_btnVideoName = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_cbVideoInputTags = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_lblVideoInputDesc = NULL;
lv_obj_t * ui_btnVideoInputDesc = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_cbVideoInputAuthor = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_btnVideoInputCancel = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_btnVideoInputOK = NULL;
lv_obj_t * ui_Label14 = NULL;
// event funtions
void ui_event_VideoInput(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        OnLoaded(e);
    }
}

void ui_event_btnVideoId(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        CommonButtonOnClick(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        CommonButtonOnLongPress(e);
    }
}

void ui_event_btnVideoName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        CommonButtonOnClick(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        CommonButtonOnLongPress(e);
    }
}

void ui_event_btnVideoInputDesc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SHORT_CLICKED) {
        CommonButtonOnClick(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        CommonButtonOnLongPress(e);
    }
}

void ui_event_btnVideoInputCancel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

void ui_event_btnVideoInputOK(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        CommonButtonOnClick(e);
    }
}

// build funtions

void ui_VideoInput_screen_init(void)
{
    ui_VideoInput = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_VideoInput, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_flex_flow(ui_VideoInput, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_VideoInput, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_VideoInput, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VideoInput, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVideoInputTitle = lv_label_create(ui_VideoInput);
    lv_obj_set_width(ui_lblVideoInputTitle, 1260);
    lv_obj_set_height(ui_lblVideoInputTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblVideoInputTitle, -46);
    lv_obj_set_y(ui_lblVideoInputTitle, 183);
    lv_obj_set_align(ui_lblVideoInputTitle, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVideoInputTitle, "New video");
    lv_obj_remove_flag(ui_lblVideoInputTitle,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblVideoInputTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVideoInputTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblVideoInputTitle, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_VideoInput);
    lv_obj_set_width(ui_Panel1, 1260);
    lv_obj_set_height(ui_Panel1, 595);
    lv_obj_set_x(ui_Panel1, -203);
    lv_obj_set_y(ui_Panel1, 194);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Panel1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Panel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label18, 285);
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -46);
    lv_obj_set_y(ui_Label18, 183);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "Video ID");
    lv_obj_remove_flag(ui_Label18, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVideoId = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_lblVideoId, 845);
    lv_obj_set_height(ui_lblVideoId, 60);
    lv_obj_set_x(ui_lblVideoId, 51);
    lv_obj_set_y(ui_lblVideoId, 183);
    lv_obj_set_align(ui_lblVideoId, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVideoId, "");
    lv_obj_remove_flag(ui_lblVideoId, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblVideoId, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVideoId, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblVideoId, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblVideoId, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblVideoId, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnVideoId = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_btnVideoId, 80);
    lv_obj_set_height(ui_btnVideoId, 80);
    lv_obj_set_x(ui_btnVideoId, -47);
    lv_obj_set_y(ui_btnVideoId, 92);
    lv_obj_set_align(ui_btnVideoId, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnVideoId, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnVideoId, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnVideoId, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnVideoId, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnVideoId, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnVideoId, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnVideoId, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnVideoId, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnVideoId, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnVideoId, &ui_img_edit_note_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnVideoId, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnVideoId, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnVideoId, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label16, 285);
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, -46);
    lv_obj_set_y(ui_Label16, 183);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Video name");
    lv_obj_remove_flag(ui_Label16, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVideoName = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_lblVideoName, 845);
    lv_obj_set_height(ui_lblVideoName, 110);
    lv_obj_set_x(ui_lblVideoName, 51);
    lv_obj_set_y(ui_lblVideoName, 183);
    lv_obj_set_align(ui_lblVideoName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVideoName, "");
    lv_obj_remove_flag(ui_lblVideoName, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblVideoName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVideoName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblVideoName, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblVideoName, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblVideoName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnVideoName = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_btnVideoName, 80);
    lv_obj_set_height(ui_btnVideoName, 80);
    lv_obj_set_x(ui_btnVideoName, -47);
    lv_obj_set_y(ui_btnVideoName, 92);
    lv_obj_set_align(ui_btnVideoName, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnVideoName, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnVideoName, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnVideoName, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnVideoName, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnVideoName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnVideoName, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnVideoName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnVideoName, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnVideoName, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnVideoName, &ui_img_edit_note_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnVideoName, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnVideoName, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnVideoName, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label17, 285);
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, -46);
    lv_obj_set_y(ui_Label17, 183);
    lv_obj_set_align(ui_Label17, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label17, "Tags");
    lv_obj_remove_flag(ui_Label17, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cbVideoInputTags = lv_dropdown_create(ui_Panel1);
    lv_dropdown_set_dir(ui_cbVideoInputTags, LV_DIR_TOP);
    lv_obj_set_width(ui_cbVideoInputTags, 845);
    lv_obj_set_height(ui_cbVideoInputTags, 75);
    lv_obj_set_align(ui_cbVideoInputTags, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cbVideoInputTags, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_cbVideoInputTags, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cbVideoInputTags, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cbVideoInputTags, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cbVideoInputTags, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cbVideoInputTags, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cbVideoInputTags, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cbVideoInputTags, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_cbVideoInputTags), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_cbVideoInputTags), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_cbVideoInputTags), &lv_font_montserrat_48,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_cbVideoInputTags), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_cbVideoInputTags), lv_color_hex(0x434343),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_cbVideoInputTags), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label19, 285);
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, -46);
    lv_obj_set_y(ui_Label19, 183);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "Description");
    lv_obj_remove_flag(ui_Label19, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lblVideoInputDesc = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_lblVideoInputDesc, 845);
    lv_obj_set_height(ui_lblVideoInputDesc, 185);
    lv_obj_set_x(ui_lblVideoInputDesc, 58);
    lv_obj_set_y(ui_lblVideoInputDesc, 205);
    lv_obj_set_align(ui_lblVideoInputDesc, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblVideoInputDesc, "");
    lv_obj_remove_flag(ui_lblVideoInputDesc,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_lblVideoInputDesc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lblVideoInputDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lblVideoInputDesc, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lblVideoInputDesc, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lblVideoInputDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnVideoInputDesc = lv_button_create(ui_Panel1);
    lv_obj_set_width(ui_btnVideoInputDesc, 80);
    lv_obj_set_height(ui_btnVideoInputDesc, 80);
    lv_obj_set_x(ui_btnVideoInputDesc, -47);
    lv_obj_set_y(ui_btnVideoInputDesc, 92);
    lv_obj_set_align(ui_btnVideoInputDesc, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnVideoInputDesc, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnVideoInputDesc, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnVideoInputDesc,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnVideoInputDesc, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnVideoInputDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnVideoInputDesc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnVideoInputDesc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnVideoInputDesc, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnVideoInputDesc, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_btnVideoInputDesc, &ui_img_edit_note_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnVideoInputDesc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnVideoInputDesc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnVideoInputDesc, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label20, 285);
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -46);
    lv_obj_set_y(ui_Label20, 183);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "Author");
    lv_obj_remove_flag(ui_Label20, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_cbVideoInputAuthor = lv_dropdown_create(ui_Panel1);
    lv_dropdown_set_dir(ui_cbVideoInputAuthor, LV_DIR_TOP);
    lv_obj_set_width(ui_cbVideoInputAuthor, 845);
    lv_obj_set_height(ui_cbVideoInputAuthor, 75);
    lv_obj_set_align(ui_cbVideoInputAuthor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cbVideoInputAuthor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_color(ui_cbVideoInputAuthor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_cbVideoInputAuthor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_cbVideoInputAuthor, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_cbVideoInputAuthor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_cbVideoInputAuthor, lv_color_hex(0x434343), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_cbVideoInputAuthor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_cbVideoInputAuthor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_dropdown_get_list(ui_cbVideoInputAuthor), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_dropdown_get_list(ui_cbVideoInputAuthor), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_cbVideoInputAuthor), &lv_font_montserrat_48,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(lv_dropdown_get_list(ui_cbVideoInputAuthor), 0,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_dropdown_get_list(ui_cbVideoInputAuthor), lv_color_hex(0x434343),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_dropdown_get_list(ui_cbVideoInputAuthor), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_VideoInput);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 1260);
    lv_obj_set_height(ui_Container2, 90);
    lv_obj_set_x(ui_Container2, 547);
    lv_obj_set_y(ui_Container2, 215);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Container2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_Container2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnVideoInputCancel = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnVideoInputCancel, 230);
    lv_obj_set_height(ui_btnVideoInputCancel, 80);
    lv_obj_set_x(ui_btnVideoInputCancel, -47);
    lv_obj_set_y(ui_btnVideoInputCancel, 92);
    lv_obj_set_align(ui_btnVideoInputCancel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnVideoInputCancel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnVideoInputCancel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnVideoInputCancel,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnVideoInputCancel, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnVideoInputCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnVideoInputCancel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnVideoInputCancel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnVideoInputCancel, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnVideoInputCancel, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnVideoInputCancel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnVideoInputCancel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnVideoInputCancel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_btnVideoInputCancel);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -46);
    lv_obj_set_y(ui_Label26, 183);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Cancel");
    lv_obj_remove_flag(ui_Label26, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnVideoInputOK = lv_button_create(ui_Container2);
    lv_obj_set_width(ui_btnVideoInputOK, 230);
    lv_obj_set_height(ui_btnVideoInputOK, 80);
    lv_obj_set_x(ui_btnVideoInputOK, -47);
    lv_obj_set_y(ui_btnVideoInputOK, 92);
    lv_obj_set_align(ui_btnVideoInputOK, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_btnVideoInputOK, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_btnVideoInputOK, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_btnVideoInputOK,
                       LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_btnVideoInputOK, lv_color_hex(0xBDBDBD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_btnVideoInputOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_btnVideoInputOK, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_btnVideoInputOK, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_btnVideoInputOK, 140, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_btnVideoInputOK, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_btnVideoInputOK, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_btnVideoInputOK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_btnVideoInputOK, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_btnVideoInputOK);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -46);
    lv_obj_set_y(ui_Label14, 183);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "OK");
    lv_obj_remove_flag(ui_Label14, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                       LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_btnVideoId, ui_event_btnVideoId, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnVideoName, ui_event_btnVideoName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnVideoInputDesc, ui_event_btnVideoInputDesc, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnVideoInputCancel, ui_event_btnVideoInputCancel, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btnVideoInputOK, ui_event_btnVideoInputOK, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VideoInput, ui_event_VideoInput, LV_EVENT_ALL, NULL);

}

void ui_VideoInput_screen_destroy(void)
{
    if(ui_VideoInput) lv_obj_del(ui_VideoInput);

    // NULL screen variables
    ui_VideoInput = NULL;
    ui_lblVideoInputTitle = NULL;
    ui_Panel1 = NULL;
    ui_Label18 = NULL;
    ui_lblVideoId = NULL;
    ui_btnVideoId = NULL;
    ui_Label16 = NULL;
    ui_lblVideoName = NULL;
    ui_btnVideoName = NULL;
    ui_Label17 = NULL;
    ui_cbVideoInputTags = NULL;
    ui_Label19 = NULL;
    ui_lblVideoInputDesc = NULL;
    ui_btnVideoInputDesc = NULL;
    ui_Label20 = NULL;
    ui_cbVideoInputAuthor = NULL;
    ui_Container2 = NULL;
    ui_btnVideoInputCancel = NULL;
    ui_Label26 = NULL;
    ui_btnVideoInputOK = NULL;
    ui_Label14 = NULL;

}
